// Generated by scripts/generate-benchmark-cache.mjs. Do not edit by hand.
export const MALATYA_C_GENERATED_ROUNDS =
[
  {
    "round": 1,
    "pairings": [
      {
        "board": 1,
        "whiteSeed": 1,
        "blackSeed": 129
      },
      {
        "board": 2,
        "whiteSeed": 130,
        "blackSeed": 2
      },
      {
        "board": 3,
        "whiteSeed": 3,
        "blackSeed": 131
      },
      {
        "board": 4,
        "whiteSeed": 132,
        "blackSeed": 4
      },
      {
        "board": 5,
        "whiteSeed": 5,
        "blackSeed": 133
      },
      {
        "board": 6,
        "whiteSeed": 134,
        "blackSeed": 6
      },
      {
        "board": 7,
        "whiteSeed": 7,
        "blackSeed": 135
      },
      {
        "board": 8,
        "whiteSeed": 136,
        "blackSeed": 8
      },
      {
        "board": 9,
        "whiteSeed": 9,
        "blackSeed": 137
      },
      {
        "board": 10,
        "whiteSeed": 138,
        "blackSeed": 10
      },
      {
        "board": 11,
        "whiteSeed": 11,
        "blackSeed": 139
      },
      {
        "board": 12,
        "whiteSeed": 140,
        "blackSeed": 12
      },
      {
        "board": 13,
        "whiteSeed": 13,
        "blackSeed": 141
      },
      {
        "board": 14,
        "whiteSeed": 142,
        "blackSeed": 14
      },
      {
        "board": 15,
        "whiteSeed": 15,
        "blackSeed": 143
      },
      {
        "board": 16,
        "whiteSeed": 144,
        "blackSeed": 16
      },
      {
        "board": 17,
        "whiteSeed": 17,
        "blackSeed": 145
      },
      {
        "board": 18,
        "whiteSeed": 146,
        "blackSeed": 18
      },
      {
        "board": 19,
        "whiteSeed": 19,
        "blackSeed": 147
      },
      {
        "board": 20,
        "whiteSeed": 148,
        "blackSeed": 20
      },
      {
        "board": 21,
        "whiteSeed": 21,
        "blackSeed": 149
      },
      {
        "board": 22,
        "whiteSeed": 150,
        "blackSeed": 22
      },
      {
        "board": 23,
        "whiteSeed": 23,
        "blackSeed": 151
      },
      {
        "board": 24,
        "whiteSeed": 152,
        "blackSeed": 24
      },
      {
        "board": 25,
        "whiteSeed": 25,
        "blackSeed": 153
      },
      {
        "board": 26,
        "whiteSeed": 154,
        "blackSeed": 26
      },
      {
        "board": 27,
        "whiteSeed": 27,
        "blackSeed": 155
      },
      {
        "board": 28,
        "whiteSeed": 156,
        "blackSeed": 28
      },
      {
        "board": 29,
        "whiteSeed": 29,
        "blackSeed": 157
      },
      {
        "board": 30,
        "whiteSeed": 158,
        "blackSeed": 30
      },
      {
        "board": 31,
        "whiteSeed": 31,
        "blackSeed": 159
      },
      {
        "board": 32,
        "whiteSeed": 160,
        "blackSeed": 32
      },
      {
        "board": 33,
        "whiteSeed": 33,
        "blackSeed": 161
      },
      {
        "board": 34,
        "whiteSeed": 162,
        "blackSeed": 34
      },
      {
        "board": 35,
        "whiteSeed": 35,
        "blackSeed": 163
      },
      {
        "board": 36,
        "whiteSeed": 164,
        "blackSeed": 36
      },
      {
        "board": 37,
        "whiteSeed": 37,
        "blackSeed": 165
      },
      {
        "board": 38,
        "whiteSeed": 166,
        "blackSeed": 38
      },
      {
        "board": 39,
        "whiteSeed": 39,
        "blackSeed": 167
      },
      {
        "board": 40,
        "whiteSeed": 168,
        "blackSeed": 40
      },
      {
        "board": 41,
        "whiteSeed": 41,
        "blackSeed": 169
      },
      {
        "board": 42,
        "whiteSeed": 170,
        "blackSeed": 42
      },
      {
        "board": 43,
        "whiteSeed": 43,
        "blackSeed": 171
      },
      {
        "board": 44,
        "whiteSeed": 172,
        "blackSeed": 44
      },
      {
        "board": 45,
        "whiteSeed": 45,
        "blackSeed": 173
      },
      {
        "board": 46,
        "whiteSeed": 174,
        "blackSeed": 46
      },
      {
        "board": 47,
        "whiteSeed": 47,
        "blackSeed": 175
      },
      {
        "board": 48,
        "whiteSeed": 176,
        "blackSeed": 48
      },
      {
        "board": 49,
        "whiteSeed": 49,
        "blackSeed": 177
      },
      {
        "board": 50,
        "whiteSeed": 178,
        "blackSeed": 50
      },
      {
        "board": 51,
        "whiteSeed": 51,
        "blackSeed": 179
      },
      {
        "board": 52,
        "whiteSeed": 180,
        "blackSeed": 52
      },
      {
        "board": 53,
        "whiteSeed": 53,
        "blackSeed": 181
      },
      {
        "board": 54,
        "whiteSeed": 182,
        "blackSeed": 54
      },
      {
        "board": 55,
        "whiteSeed": 55,
        "blackSeed": 183
      },
      {
        "board": 56,
        "whiteSeed": 184,
        "blackSeed": 56
      },
      {
        "board": 57,
        "whiteSeed": 57,
        "blackSeed": 185
      },
      {
        "board": 58,
        "whiteSeed": 186,
        "blackSeed": 58
      },
      {
        "board": 59,
        "whiteSeed": 59,
        "blackSeed": 187
      },
      {
        "board": 60,
        "whiteSeed": 188,
        "blackSeed": 60
      },
      {
        "board": 61,
        "whiteSeed": 61,
        "blackSeed": 189
      },
      {
        "board": 62,
        "whiteSeed": 190,
        "blackSeed": 62
      },
      {
        "board": 63,
        "whiteSeed": 63,
        "blackSeed": 191
      },
      {
        "board": 64,
        "whiteSeed": 192,
        "blackSeed": 64
      },
      {
        "board": 65,
        "whiteSeed": 65,
        "blackSeed": 193
      },
      {
        "board": 66,
        "whiteSeed": 194,
        "blackSeed": 66
      },
      {
        "board": 67,
        "whiteSeed": 67,
        "blackSeed": 195
      },
      {
        "board": 68,
        "whiteSeed": 196,
        "blackSeed": 68
      },
      {
        "board": 69,
        "whiteSeed": 69,
        "blackSeed": 197
      },
      {
        "board": 70,
        "whiteSeed": 198,
        "blackSeed": 70
      },
      {
        "board": 71,
        "whiteSeed": 71,
        "blackSeed": 199
      },
      {
        "board": 72,
        "whiteSeed": 200,
        "blackSeed": 72
      },
      {
        "board": 73,
        "whiteSeed": 73,
        "blackSeed": 201
      },
      {
        "board": 74,
        "whiteSeed": 202,
        "blackSeed": 74
      },
      {
        "board": 75,
        "whiteSeed": 75,
        "blackSeed": 203
      },
      {
        "board": 76,
        "whiteSeed": 204,
        "blackSeed": 76
      },
      {
        "board": 77,
        "whiteSeed": 77,
        "blackSeed": 205
      },
      {
        "board": 78,
        "whiteSeed": 206,
        "blackSeed": 78
      },
      {
        "board": 79,
        "whiteSeed": 79,
        "blackSeed": 207
      },
      {
        "board": 80,
        "whiteSeed": 208,
        "blackSeed": 80
      },
      {
        "board": 81,
        "whiteSeed": 81,
        "blackSeed": 209
      },
      {
        "board": 82,
        "whiteSeed": 210,
        "blackSeed": 82
      },
      {
        "board": 83,
        "whiteSeed": 83,
        "blackSeed": 211
      },
      {
        "board": 84,
        "whiteSeed": 212,
        "blackSeed": 84
      },
      {
        "board": 85,
        "whiteSeed": 85,
        "blackSeed": 214
      },
      {
        "board": 86,
        "whiteSeed": 215,
        "blackSeed": 86
      },
      {
        "board": 87,
        "whiteSeed": 87,
        "blackSeed": 216
      },
      {
        "board": 88,
        "whiteSeed": 217,
        "blackSeed": 88
      },
      {
        "board": 89,
        "whiteSeed": 89,
        "blackSeed": 218
      },
      {
        "board": 90,
        "whiteSeed": 219,
        "blackSeed": 90
      },
      {
        "board": 91,
        "whiteSeed": 91,
        "blackSeed": 220
      },
      {
        "board": 92,
        "whiteSeed": 221,
        "blackSeed": 92
      },
      {
        "board": 93,
        "whiteSeed": 93,
        "blackSeed": 222
      },
      {
        "board": 94,
        "whiteSeed": 223,
        "blackSeed": 94
      },
      {
        "board": 95,
        "whiteSeed": 95,
        "blackSeed": 224
      },
      {
        "board": 96,
        "whiteSeed": 225,
        "blackSeed": 96
      },
      {
        "board": 97,
        "whiteSeed": 97,
        "blackSeed": 226
      },
      {
        "board": 98,
        "whiteSeed": 227,
        "blackSeed": 98
      },
      {
        "board": 99,
        "whiteSeed": 99,
        "blackSeed": 228
      },
      {
        "board": 100,
        "whiteSeed": 229,
        "blackSeed": 100
      },
      {
        "board": 101,
        "whiteSeed": 101,
        "blackSeed": 230
      },
      {
        "board": 102,
        "whiteSeed": 231,
        "blackSeed": 102
      },
      {
        "board": 103,
        "whiteSeed": 103,
        "blackSeed": 232
      },
      {
        "board": 104,
        "whiteSeed": 233,
        "blackSeed": 104
      },
      {
        "board": 105,
        "whiteSeed": 105,
        "blackSeed": 234
      },
      {
        "board": 106,
        "whiteSeed": 235,
        "blackSeed": 106
      },
      {
        "board": 107,
        "whiteSeed": 107,
        "blackSeed": 236
      },
      {
        "board": 108,
        "whiteSeed": 237,
        "blackSeed": 108
      },
      {
        "board": 109,
        "whiteSeed": 109,
        "blackSeed": 238
      },
      {
        "board": 110,
        "whiteSeed": 239,
        "blackSeed": 110
      },
      {
        "board": 111,
        "whiteSeed": 111,
        "blackSeed": 240
      },
      {
        "board": 112,
        "whiteSeed": 241,
        "blackSeed": 112
      },
      {
        "board": 113,
        "whiteSeed": 113,
        "blackSeed": 242
      },
      {
        "board": 114,
        "whiteSeed": 243,
        "blackSeed": 114
      },
      {
        "board": 115,
        "whiteSeed": 115,
        "blackSeed": 244
      },
      {
        "board": 116,
        "whiteSeed": 245,
        "blackSeed": 116
      },
      {
        "board": 117,
        "whiteSeed": 117,
        "blackSeed": 246
      },
      {
        "board": 118,
        "whiteSeed": 247,
        "blackSeed": 118
      },
      {
        "board": 119,
        "whiteSeed": 119,
        "blackSeed": 248
      },
      {
        "board": 120,
        "whiteSeed": 249,
        "blackSeed": 120
      },
      {
        "board": 121,
        "whiteSeed": 121,
        "blackSeed": 250
      },
      {
        "board": 122,
        "whiteSeed": 251,
        "blackSeed": 122
      },
      {
        "board": 123,
        "whiteSeed": 123,
        "blackSeed": 252
      },
      {
        "board": 124,
        "whiteSeed": 253,
        "blackSeed": 124
      },
      {
        "board": 125,
        "whiteSeed": 125,
        "blackSeed": 254
      },
      {
        "board": 126,
        "whiteSeed": 255,
        "blackSeed": 126
      },
      {
        "board": 127,
        "whiteSeed": 127,
        "blackSeed": 256
      },
      {
        "board": 128,
        "whiteSeed": 257,
        "blackSeed": 128
      },
      {
        "board": 129,
        "whiteSeed": 213,
        "blackSeed": null
      }
    ]
  },
  {
    "round": 2,
    "pairings": [
      {
        "board": 1,
        "whiteSeed": 76,
        "blackSeed": 1
      },
      {
        "board": 2,
        "whiteSeed": 2,
        "blackSeed": 77
      },
      {
        "board": 3,
        "whiteSeed": 78,
        "blackSeed": 5
      },
      {
        "board": 4,
        "whiteSeed": 6,
        "blackSeed": 79
      },
      {
        "board": 5,
        "whiteSeed": 80,
        "blackSeed": 7
      },
      {
        "board": 6,
        "whiteSeed": 8,
        "blackSeed": 81
      },
      {
        "board": 7,
        "whiteSeed": 82,
        "blackSeed": 9
      },
      {
        "board": 8,
        "whiteSeed": 10,
        "blackSeed": 83
      },
      {
        "board": 9,
        "whiteSeed": 12,
        "blackSeed": 85
      },
      {
        "board": 10,
        "whiteSeed": 84,
        "blackSeed": 13
      },
      {
        "board": 11,
        "whiteSeed": 14,
        "blackSeed": 89
      },
      {
        "board": 12,
        "whiteSeed": 88,
        "blackSeed": 15
      },
      {
        "board": 13,
        "whiteSeed": 16,
        "blackSeed": 91
      },
      {
        "board": 14,
        "whiteSeed": 90,
        "blackSeed": 17
      },
      {
        "board": 15,
        "whiteSeed": 18,
        "blackSeed": 93
      },
      {
        "board": 16,
        "whiteSeed": 92,
        "blackSeed": 19
      },
      {
        "board": 17,
        "whiteSeed": 21,
        "blackSeed": 95
      },
      {
        "board": 18,
        "whiteSeed": 94,
        "blackSeed": 23
      },
      {
        "board": 19,
        "whiteSeed": 96,
        "blackSeed": 25
      },
      {
        "board": 20,
        "whiteSeed": 28,
        "blackSeed": 97
      },
      {
        "board": 21,
        "whiteSeed": 30,
        "blackSeed": 99
      },
      {
        "board": 22,
        "whiteSeed": 100,
        "blackSeed": 31
      },
      {
        "board": 23,
        "whiteSeed": 32,
        "blackSeed": 103
      },
      {
        "board": 24,
        "whiteSeed": 102,
        "blackSeed": 33
      },
      {
        "board": 25,
        "whiteSeed": 34,
        "blackSeed": 105
      },
      {
        "board": 26,
        "whiteSeed": 104,
        "blackSeed": 35
      },
      {
        "board": 27,
        "whiteSeed": 36,
        "blackSeed": 107
      },
      {
        "board": 28,
        "whiteSeed": 106,
        "blackSeed": 37
      },
      {
        "board": 29,
        "whiteSeed": 38,
        "blackSeed": 109
      },
      {
        "board": 30,
        "whiteSeed": 40,
        "blackSeed": 111
      },
      {
        "board": 31,
        "whiteSeed": 110,
        "blackSeed": 41
      },
      {
        "board": 32,
        "whiteSeed": 112,
        "blackSeed": 43
      },
      {
        "board": 33,
        "whiteSeed": 44,
        "blackSeed": 113
      },
      {
        "board": 34,
        "whiteSeed": 114,
        "blackSeed": 45
      },
      {
        "board": 35,
        "whiteSeed": 46,
        "blackSeed": 115
      },
      {
        "board": 36,
        "whiteSeed": 116,
        "blackSeed": 47
      },
      {
        "board": 37,
        "whiteSeed": 48,
        "blackSeed": 117
      },
      {
        "board": 38,
        "whiteSeed": 118,
        "blackSeed": 49
      },
      {
        "board": 39,
        "whiteSeed": 50,
        "blackSeed": 119
      },
      {
        "board": 40,
        "whiteSeed": 121,
        "blackSeed": 51
      },
      {
        "board": 41,
        "whiteSeed": 122,
        "blackSeed": 53
      },
      {
        "board": 42,
        "whiteSeed": 54,
        "blackSeed": 123
      },
      {
        "board": 43,
        "whiteSeed": 124,
        "blackSeed": 55
      },
      {
        "board": 44,
        "whiteSeed": 56,
        "blackSeed": 125
      },
      {
        "board": 45,
        "whiteSeed": 126,
        "blackSeed": 57
      },
      {
        "board": 46,
        "whiteSeed": 58,
        "blackSeed": 127
      },
      {
        "board": 47,
        "whiteSeed": 130,
        "blackSeed": 59
      },
      {
        "board": 48,
        "whiteSeed": 60,
        "blackSeed": 147
      },
      {
        "board": 49,
        "whiteSeed": 149,
        "blackSeed": 61
      },
      {
        "board": 50,
        "whiteSeed": 153,
        "blackSeed": 63
      },
      {
        "board": 51,
        "whiteSeed": 64,
        "blackSeed": 179
      },
      {
        "board": 52,
        "whiteSeed": 156,
        "blackSeed": 65
      },
      {
        "board": 53,
        "whiteSeed": 66,
        "blackSeed": 189
      },
      {
        "board": 54,
        "whiteSeed": 200,
        "blackSeed": 67
      },
      {
        "board": 55,
        "whiteSeed": 68,
        "blackSeed": 214
      },
      {
        "board": 56,
        "whiteSeed": 213,
        "blackSeed": 69
      },
      {
        "board": 57,
        "whiteSeed": 70,
        "blackSeed": 249
      },
      {
        "board": 58,
        "whiteSeed": 215,
        "blackSeed": 71
      },
      {
        "board": 59,
        "whiteSeed": 72,
        "blackSeed": 257
      },
      {
        "board": 60,
        "whiteSeed": 230,
        "blackSeed": 75
      },
      {
        "board": 61,
        "whiteSeed": 4,
        "blackSeed": 151
      },
      {
        "board": 62,
        "whiteSeed": 154,
        "blackSeed": 11
      },
      {
        "board": 63,
        "whiteSeed": 24,
        "blackSeed": 131
      },
      {
        "board": 64,
        "whiteSeed": 166,
        "blackSeed": 27
      },
      {
        "board": 65,
        "whiteSeed": 138,
        "blackSeed": 39
      },
      {
        "board": 66,
        "whiteSeed": 42,
        "blackSeed": 201
      },
      {
        "board": 67,
        "whiteSeed": 74,
        "blackSeed": 169
      },
      {
        "board": 68,
        "whiteSeed": 98,
        "blackSeed": 237
      },
      {
        "board": 69,
        "whiteSeed": 108,
        "blackSeed": 227
      },
      {
        "board": 70,
        "whiteSeed": 188,
        "blackSeed": 3
      },
      {
        "board": 71,
        "whiteSeed": 20,
        "blackSeed": 190
      },
      {
        "board": 72,
        "whiteSeed": 22,
        "blackSeed": 191
      },
      {
        "board": 73,
        "whiteSeed": 26,
        "blackSeed": 192
      },
      {
        "board": 74,
        "whiteSeed": 194,
        "blackSeed": 29
      },
      {
        "board": 75,
        "whiteSeed": 52,
        "blackSeed": 193
      },
      {
        "board": 76,
        "whiteSeed": 62,
        "blackSeed": 195
      },
      {
        "board": 77,
        "whiteSeed": 196,
        "blackSeed": 73
      },
      {
        "board": 78,
        "whiteSeed": 86,
        "blackSeed": 197
      },
      {
        "board": 79,
        "whiteSeed": 198,
        "blackSeed": 87
      },
      {
        "board": 80,
        "whiteSeed": 202,
        "blackSeed": 101
      },
      {
        "board": 81,
        "whiteSeed": 120,
        "blackSeed": 199
      },
      {
        "board": 82,
        "whiteSeed": 128,
        "blackSeed": 203
      },
      {
        "board": 83,
        "whiteSeed": 204,
        "blackSeed": 129
      },
      {
        "board": 84,
        "whiteSeed": 132,
        "blackSeed": 205
      },
      {
        "board": 85,
        "whiteSeed": 206,
        "blackSeed": 133
      },
      {
        "board": 86,
        "whiteSeed": 134,
        "blackSeed": 207
      },
      {
        "board": 87,
        "whiteSeed": 208,
        "blackSeed": 135
      },
      {
        "board": 88,
        "whiteSeed": 136,
        "blackSeed": 209
      },
      {
        "board": 89,
        "whiteSeed": 210,
        "blackSeed": 137
      },
      {
        "board": 90,
        "whiteSeed": 212,
        "blackSeed": 139
      },
      {
        "board": 91,
        "whiteSeed": 140,
        "blackSeed": 211
      },
      {
        "board": 92,
        "whiteSeed": 216,
        "blackSeed": 141
      },
      {
        "board": 93,
        "whiteSeed": 142,
        "blackSeed": 217
      },
      {
        "board": 94,
        "whiteSeed": 218,
        "blackSeed": 143
      },
      {
        "board": 95,
        "whiteSeed": 144,
        "blackSeed": 219
      },
      {
        "board": 96,
        "whiteSeed": 220,
        "blackSeed": 145
      },
      {
        "board": 97,
        "whiteSeed": 146,
        "blackSeed": 221
      },
      {
        "board": 98,
        "whiteSeed": 150,
        "blackSeed": 222
      },
      {
        "board": 99,
        "whiteSeed": 152,
        "blackSeed": 223
      },
      {
        "board": 100,
        "whiteSeed": 224,
        "blackSeed": 155
      },
      {
        "board": 101,
        "whiteSeed": 226,
        "blackSeed": 157
      },
      {
        "board": 102,
        "whiteSeed": 158,
        "blackSeed": 225
      },
      {
        "board": 103,
        "whiteSeed": 228,
        "blackSeed": 159
      },
      {
        "board": 104,
        "whiteSeed": 160,
        "blackSeed": 229
      },
      {
        "board": 105,
        "whiteSeed": 232,
        "blackSeed": 161
      },
      {
        "board": 106,
        "whiteSeed": 162,
        "blackSeed": 231
      },
      {
        "board": 107,
        "whiteSeed": 234,
        "blackSeed": 163
      },
      {
        "board": 108,
        "whiteSeed": 164,
        "blackSeed": 233
      },
      {
        "board": 109,
        "whiteSeed": 236,
        "blackSeed": 165
      },
      {
        "board": 110,
        "whiteSeed": 238,
        "blackSeed": 167
      },
      {
        "board": 111,
        "whiteSeed": 168,
        "blackSeed": 235
      },
      {
        "board": 112,
        "whiteSeed": 170,
        "blackSeed": 239
      },
      {
        "board": 113,
        "whiteSeed": 240,
        "blackSeed": 171
      },
      {
        "board": 114,
        "whiteSeed": 172,
        "blackSeed": 241
      },
      {
        "board": 115,
        "whiteSeed": 242,
        "blackSeed": 173
      },
      {
        "board": 116,
        "whiteSeed": 174,
        "blackSeed": 243
      },
      {
        "board": 117,
        "whiteSeed": 244,
        "blackSeed": 175
      },
      {
        "board": 118,
        "whiteSeed": 176,
        "blackSeed": 245
      },
      {
        "board": 119,
        "whiteSeed": 246,
        "blackSeed": 177
      },
      {
        "board": 120,
        "whiteSeed": 178,
        "blackSeed": 247
      },
      {
        "board": 121,
        "whiteSeed": 180,
        "blackSeed": 248
      },
      {
        "board": 122,
        "whiteSeed": 250,
        "blackSeed": 181
      },
      {
        "board": 123,
        "whiteSeed": 182,
        "blackSeed": 251
      },
      {
        "board": 124,
        "whiteSeed": 252,
        "blackSeed": 183
      },
      {
        "board": 125,
        "whiteSeed": 184,
        "blackSeed": 253
      },
      {
        "board": 126,
        "whiteSeed": 254,
        "blackSeed": 185
      },
      {
        "board": 127,
        "whiteSeed": 186,
        "blackSeed": 255
      },
      {
        "board": 128,
        "whiteSeed": 256,
        "blackSeed": 187
      }
    ]
  },
  {
    "round": 3,
    "pairings": [
      {
        "board": 1,
        "whiteSeed": 56,
        "blackSeed": 2
      },
      {
        "board": 2,
        "whiteSeed": 59,
        "blackSeed": 6
      },
      {
        "board": 3,
        "whiteSeed": 61,
        "blackSeed": 8
      },
      {
        "board": 4,
        "whiteSeed": 63,
        "blackSeed": 10
      },
      {
        "board": 5,
        "whiteSeed": 64,
        "blackSeed": 12
      },
      {
        "board": 6,
        "whiteSeed": 13,
        "blackSeed": 66
      },
      {
        "board": 7,
        "whiteSeed": 15,
        "blackSeed": 68
      },
      {
        "board": 8,
        "whiteSeed": 17,
        "blackSeed": 70
      },
      {
        "board": 9,
        "whiteSeed": 67,
        "blackSeed": 18
      },
      {
        "board": 10,
        "whiteSeed": 69,
        "blackSeed": 21
      },
      {
        "board": 11,
        "whiteSeed": 25,
        "blackSeed": 76
      },
      {
        "board": 12,
        "whiteSeed": 71,
        "blackSeed": 28
      },
      {
        "board": 13,
        "whiteSeed": 31,
        "blackSeed": 82
      },
      {
        "board": 14,
        "whiteSeed": 75,
        "blackSeed": 32
      },
      {
        "board": 15,
        "whiteSeed": 33,
        "blackSeed": 92
      },
      {
        "board": 16,
        "whiteSeed": 35,
        "blackSeed": 94
      },
      {
        "board": 17,
        "whiteSeed": 89,
        "blackSeed": 36
      },
      {
        "board": 18,
        "whiteSeed": 37,
        "blackSeed": 114
      },
      {
        "board": 19,
        "whiteSeed": 91,
        "blackSeed": 38
      },
      {
        "board": 20,
        "whiteSeed": 99,
        "blackSeed": 40
      },
      {
        "board": 21,
        "whiteSeed": 41,
        "blackSeed": 118
      },
      {
        "board": 22,
        "whiteSeed": 43,
        "blackSeed": 122
      },
      {
        "board": 23,
        "whiteSeed": 119,
        "blackSeed": 44
      },
      {
        "board": 24,
        "whiteSeed": 124,
        "blackSeed": 46
      },
      {
        "board": 25,
        "whiteSeed": 126,
        "blackSeed": 48
      },
      {
        "board": 26,
        "whiteSeed": 51,
        "blackSeed": 156
      },
      {
        "board": 27,
        "whiteSeed": 127,
        "blackSeed": 54
      },
      {
        "board": 28,
        "whiteSeed": 105,
        "blackSeed": 4
      },
      {
        "board": 29,
        "whiteSeed": 5,
        "blackSeed": 80
      },
      {
        "board": 30,
        "whiteSeed": 7,
        "blackSeed": 98
      },
      {
        "board": 31,
        "whiteSeed": 11,
        "blackSeed": 108
      },
      {
        "board": 32,
        "whiteSeed": 27,
        "blackSeed": 116
      },
      {
        "board": 33,
        "whiteSeed": 131,
        "blackSeed": 34
      },
      {
        "board": 34,
        "whiteSeed": 47,
        "blackSeed": 201
      },
      {
        "board": 35,
        "whiteSeed": 169,
        "blackSeed": 60
      },
      {
        "board": 36,
        "whiteSeed": 147,
        "blackSeed": 72
      },
      {
        "board": 37,
        "whiteSeed": 257,
        "blackSeed": 78
      },
      {
        "board": 38,
        "whiteSeed": 1,
        "blackSeed": 129
      },
      {
        "board": 39,
        "whiteSeed": 3,
        "blackSeed": 132
      },
      {
        "board": 40,
        "whiteSeed": 9,
        "blackSeed": 130
      },
      {
        "board": 41,
        "whiteSeed": 133,
        "blackSeed": 14
      },
      {
        "board": 42,
        "whiteSeed": 135,
        "blackSeed": 16
      },
      {
        "board": 43,
        "whiteSeed": 19,
        "blackSeed": 136
      },
      {
        "board": 44,
        "whiteSeed": 137,
        "blackSeed": 20
      },
      {
        "board": 45,
        "whiteSeed": 139,
        "blackSeed": 22
      },
      {
        "board": 46,
        "whiteSeed": 23,
        "blackSeed": 138
      },
      {
        "board": 47,
        "whiteSeed": 141,
        "blackSeed": 26
      },
      {
        "board": 48,
        "whiteSeed": 29,
        "blackSeed": 140
      },
      {
        "board": 49,
        "whiteSeed": 143,
        "blackSeed": 30
      },
      {
        "board": 50,
        "whiteSeed": 39,
        "blackSeed": 142
      },
      {
        "board": 51,
        "whiteSeed": 45,
        "blackSeed": 145
      },
      {
        "board": 52,
        "whiteSeed": 49,
        "blackSeed": 149
      },
      {
        "board": 53,
        "whiteSeed": 155,
        "blackSeed": 50
      },
      {
        "board": 54,
        "whiteSeed": 161,
        "blackSeed": 52
      },
      {
        "board": 55,
        "whiteSeed": 53,
        "blackSeed": 153
      },
      {
        "board": 56,
        "whiteSeed": 55,
        "blackSeed": 160
      },
      {
        "board": 57,
        "whiteSeed": 57,
        "blackSeed": 162
      },
      {
        "board": 58,
        "whiteSeed": 163,
        "blackSeed": 58
      },
      {
        "board": 59,
        "whiteSeed": 167,
        "blackSeed": 62
      },
      {
        "board": 60,
        "whiteSeed": 65,
        "blackSeed": 168
      },
      {
        "board": 61,
        "whiteSeed": 73,
        "blackSeed": 170
      },
      {
        "board": 62,
        "whiteSeed": 77,
        "blackSeed": 171
      },
      {
        "board": 63,
        "whiteSeed": 79,
        "blackSeed": 172
      },
      {
        "board": 64,
        "whiteSeed": 81,
        "blackSeed": 173
      },
      {
        "board": 65,
        "whiteSeed": 83,
        "blackSeed": 174
      },
      {
        "board": 66,
        "whiteSeed": 175,
        "blackSeed": 84
      },
      {
        "board": 67,
        "whiteSeed": 85,
        "blackSeed": 177
      },
      {
        "board": 68,
        "whiteSeed": 179,
        "blackSeed": 86
      },
      {
        "board": 69,
        "whiteSeed": 87,
        "blackSeed": 178
      },
      {
        "board": 70,
        "whiteSeed": 180,
        "blackSeed": 88
      },
      {
        "board": 71,
        "whiteSeed": 181,
        "blackSeed": 90
      },
      {
        "board": 72,
        "whiteSeed": 93,
        "blackSeed": 182
      },
      {
        "board": 73,
        "whiteSeed": 95,
        "blackSeed": 183
      },
      {
        "board": 74,
        "whiteSeed": 187,
        "blackSeed": 96
      },
      {
        "board": 75,
        "whiteSeed": 97,
        "blackSeed": 186
      },
      {
        "board": 76,
        "whiteSeed": 189,
        "blackSeed": 100
      },
      {
        "board": 77,
        "whiteSeed": 101,
        "blackSeed": 199
      },
      {
        "board": 78,
        "whiteSeed": 214,
        "blackSeed": 102
      },
      {
        "board": 79,
        "whiteSeed": 103,
        "blackSeed": 200
      },
      {
        "board": 80,
        "whiteSeed": 219,
        "blackSeed": 104
      },
      {
        "board": 81,
        "whiteSeed": 221,
        "blackSeed": 106
      },
      {
        "board": 82,
        "whiteSeed": 107,
        "blackSeed": 213
      },
      {
        "board": 83,
        "whiteSeed": 109,
        "blackSeed": 215
      },
      {
        "board": 84,
        "whiteSeed": 222,
        "blackSeed": 110
      },
      {
        "board": 85,
        "whiteSeed": 111,
        "blackSeed": 223
      },
      {
        "board": 86,
        "whiteSeed": 225,
        "blackSeed": 112
      },
      {
        "board": 87,
        "whiteSeed": 113,
        "blackSeed": 226
      },
      {
        "board": 88,
        "whiteSeed": 115,
        "blackSeed": 228
      },
      {
        "board": 89,
        "whiteSeed": 117,
        "blackSeed": 230
      },
      {
        "board": 90,
        "whiteSeed": 245,
        "blackSeed": 121
      },
      {
        "board": 91,
        "whiteSeed": 123,
        "blackSeed": 254
      },
      {
        "board": 92,
        "whiteSeed": 125,
        "blackSeed": 236
      },
      {
        "board": 93,
        "whiteSeed": 249,
        "blackSeed": 128
      },
      {
        "board": 94,
        "whiteSeed": 253,
        "blackSeed": 24
      },
      {
        "board": 95,
        "whiteSeed": 207,
        "blackSeed": 74
      },
      {
        "board": 96,
        "whiteSeed": 227,
        "blackSeed": 134
      },
      {
        "board": 97,
        "whiteSeed": 151,
        "blackSeed": 166
      },
      {
        "board": 98,
        "whiteSeed": 233,
        "blackSeed": 154
      },
      {
        "board": 99,
        "whiteSeed": 237,
        "blackSeed": 164
      },
      {
        "board": 100,
        "whiteSeed": 209,
        "blackSeed": 120
      },
      {
        "board": 101,
        "whiteSeed": 210,
        "blackSeed": 144
      },
      {
        "board": 102,
        "whiteSeed": 211,
        "blackSeed": 146
      },
      {
        "board": 103,
        "whiteSeed": 212,
        "blackSeed": 150
      },
      {
        "board": 104,
        "whiteSeed": 217,
        "blackSeed": 152
      },
      {
        "board": 105,
        "whiteSeed": 157,
        "blackSeed": 216
      },
      {
        "board": 106,
        "whiteSeed": 229,
        "blackSeed": 158
      },
      {
        "board": 107,
        "whiteSeed": 159,
        "blackSeed": 218
      },
      {
        "board": 108,
        "whiteSeed": 165,
        "blackSeed": 220
      },
      {
        "board": 109,
        "whiteSeed": 231,
        "blackSeed": 176
      },
      {
        "board": 110,
        "whiteSeed": 235,
        "blackSeed": 184
      },
      {
        "board": 111,
        "whiteSeed": 185,
        "blackSeed": 224
      },
      {
        "board": 112,
        "whiteSeed": 239,
        "blackSeed": 188
      },
      {
        "board": 113,
        "whiteSeed": 190,
        "blackSeed": 232
      },
      {
        "board": 114,
        "whiteSeed": 191,
        "blackSeed": 234
      },
      {
        "board": 115,
        "whiteSeed": 192,
        "blackSeed": 238
      },
      {
        "board": 116,
        "whiteSeed": 193,
        "blackSeed": 240
      },
      {
        "board": 117,
        "whiteSeed": 241,
        "blackSeed": 194
      },
      {
        "board": 118,
        "whiteSeed": 195,
        "blackSeed": 244
      },
      {
        "board": 119,
        "whiteSeed": 242,
        "blackSeed": 196
      },
      {
        "board": 120,
        "whiteSeed": 197,
        "blackSeed": 246
      },
      {
        "board": 121,
        "whiteSeed": 243,
        "blackSeed": 198
      },
      {
        "board": 122,
        "whiteSeed": 247,
        "blackSeed": 202
      },
      {
        "board": 123,
        "whiteSeed": 203,
        "blackSeed": 250
      },
      {
        "board": 124,
        "whiteSeed": 248,
        "blackSeed": 204
      },
      {
        "board": 125,
        "whiteSeed": 205,
        "blackSeed": 252
      },
      {
        "board": 126,
        "whiteSeed": 251,
        "blackSeed": 206
      },
      {
        "board": 127,
        "whiteSeed": 255,
        "blackSeed": 208
      },
      {
        "board": 128,
        "whiteSeed": 256,
        "blackSeed": null
      }
    ]
  },
  {
    "round": 4,
    "pairings": [
      {
        "board": 1,
        "whiteSeed": 2,
        "blackSeed": 63
      },
      {
        "board": 2,
        "whiteSeed": 12,
        "blackSeed": 67
      },
      {
        "board": 3,
        "whiteSeed": 69,
        "blackSeed": 13
      },
      {
        "board": 4,
        "whiteSeed": 70,
        "blackSeed": 15
      },
      {
        "board": 5,
        "whiteSeed": 28,
        "blackSeed": 89
      },
      {
        "board": 6,
        "whiteSeed": 32,
        "blackSeed": 91
      },
      {
        "board": 7,
        "whiteSeed": 82,
        "blackSeed": 33
      },
      {
        "board": 8,
        "whiteSeed": 94,
        "blackSeed": 37
      },
      {
        "board": 9,
        "whiteSeed": 40,
        "blackSeed": 119
      },
      {
        "board": 10,
        "whiteSeed": 118,
        "blackSeed": 43
      },
      {
        "board": 11,
        "whiteSeed": 46,
        "blackSeed": 126
      },
      {
        "board": 12,
        "whiteSeed": 127,
        "blackSeed": 59
      },
      {
        "board": 13,
        "whiteSeed": 156,
        "blackSeed": 61
      },
      {
        "board": 14,
        "whiteSeed": 60,
        "blackSeed": 7
      },
      {
        "board": 15,
        "whiteSeed": 72,
        "blackSeed": 11
      },
      {
        "board": 16,
        "whiteSeed": 80,
        "blackSeed": 25
      },
      {
        "board": 17,
        "whiteSeed": 76,
        "blackSeed": 27
      },
      {
        "board": 18,
        "whiteSeed": 34,
        "blackSeed": 257
      },
      {
        "board": 19,
        "whiteSeed": 84,
        "blackSeed": 1
      },
      {
        "board": 20,
        "whiteSeed": 86,
        "blackSeed": 3
      },
      {
        "board": 21,
        "whiteSeed": 4,
        "blackSeed": 75
      },
      {
        "board": 22,
        "whiteSeed": 6,
        "blackSeed": 77
      },
      {
        "board": 23,
        "whiteSeed": 8,
        "blackSeed": 79
      },
      {
        "board": 24,
        "whiteSeed": 88,
        "blackSeed": 9
      },
      {
        "board": 25,
        "whiteSeed": 10,
        "blackSeed": 81
      },
      {
        "board": 26,
        "whiteSeed": 14,
        "blackSeed": 83
      },
      {
        "board": 27,
        "whiteSeed": 16,
        "blackSeed": 85
      },
      {
        "board": 28,
        "whiteSeed": 92,
        "blackSeed": 17
      },
      {
        "board": 29,
        "whiteSeed": 18,
        "blackSeed": 95
      },
      {
        "board": 30,
        "whiteSeed": 90,
        "blackSeed": 19
      },
      {
        "board": 31,
        "whiteSeed": 20,
        "blackSeed": 93
      },
      {
        "board": 32,
        "whiteSeed": 21,
        "blackSeed": 99
      },
      {
        "board": 33,
        "whiteSeed": 22,
        "blackSeed": 105
      },
      {
        "board": 34,
        "whiteSeed": 26,
        "blackSeed": 109
      },
      {
        "board": 35,
        "whiteSeed": 96,
        "blackSeed": 29
      },
      {
        "board": 36,
        "whiteSeed": 30,
        "blackSeed": 111
      },
      {
        "board": 37,
        "whiteSeed": 104,
        "blackSeed": 31
      },
      {
        "board": 38,
        "whiteSeed": 100,
        "blackSeed": 35
      },
      {
        "board": 39,
        "whiteSeed": 36,
        "blackSeed": 113
      },
      {
        "board": 40,
        "whiteSeed": 38,
        "blackSeed": 115
      },
      {
        "board": 41,
        "whiteSeed": 106,
        "blackSeed": 39
      },
      {
        "board": 42,
        "whiteSeed": 107,
        "blackSeed": 41
      },
      {
        "board": 43,
        "whiteSeed": 44,
        "blackSeed": 121
      },
      {
        "board": 44,
        "whiteSeed": 110,
        "blackSeed": 47
      },
      {
        "board": 45,
        "whiteSeed": 48,
        "blackSeed": 123
      },
      {
        "board": 46,
        "whiteSeed": 50,
        "blackSeed": 124
      },
      {
        "board": 47,
        "whiteSeed": 112,
        "blackSeed": 51
      },
      {
        "board": 48,
        "whiteSeed": 52,
        "blackSeed": 125
      },
      {
        "board": 49,
        "whiteSeed": 54,
        "blackSeed": 153
      },
      {
        "board": 50,
        "whiteSeed": 114,
        "blackSeed": 55
      },
      {
        "board": 51,
        "whiteSeed": 122,
        "blackSeed": 56
      },
      {
        "board": 52,
        "whiteSeed": 138,
        "blackSeed": 57
      },
      {
        "board": 53,
        "whiteSeed": 62,
        "blackSeed": 163
      },
      {
        "board": 54,
        "whiteSeed": 178,
        "blackSeed": 64
      },
      {
        "board": 55,
        "whiteSeed": 186,
        "blackSeed": 65
      },
      {
        "board": 56,
        "whiteSeed": 66,
        "blackSeed": 214
      },
      {
        "board": 57,
        "whiteSeed": 68,
        "blackSeed": 249
      },
      {
        "board": 58,
        "whiteSeed": 199,
        "blackSeed": 71
      },
      {
        "board": 59,
        "whiteSeed": 201,
        "blackSeed": 73
      },
      {
        "board": 60,
        "whiteSeed": 230,
        "blackSeed": 5
      },
      {
        "board": 61,
        "whiteSeed": 24,
        "blackSeed": 147
      },
      {
        "board": 62,
        "whiteSeed": 154,
        "blackSeed": 45
      },
      {
        "board": 63,
        "whiteSeed": 145,
        "blackSeed": 49
      },
      {
        "board": 64,
        "whiteSeed": 74,
        "blackSeed": 131
      },
      {
        "board": 65,
        "whiteSeed": 78,
        "blackSeed": 149
      },
      {
        "board": 66,
        "whiteSeed": 98,
        "blackSeed": 151
      },
      {
        "board": 67,
        "whiteSeed": 164,
        "blackSeed": 103
      },
      {
        "board": 68,
        "whiteSeed": 108,
        "blackSeed": 169
      },
      {
        "board": 69,
        "whiteSeed": 116,
        "blackSeed": 227
      },
      {
        "board": 70,
        "whiteSeed": 200,
        "blackSeed": 23
      },
      {
        "board": 71,
        "whiteSeed": 176,
        "blackSeed": 53
      },
      {
        "board": 72,
        "whiteSeed": 58,
        "blackSeed": 175
      },
      {
        "board": 73,
        "whiteSeed": 177,
        "blackSeed": 87
      },
      {
        "board": 74,
        "whiteSeed": 182,
        "blackSeed": 97
      },
      {
        "board": 75,
        "whiteSeed": 183,
        "blackSeed": 101
      },
      {
        "board": 76,
        "whiteSeed": 102,
        "blackSeed": 179
      },
      {
        "board": 77,
        "whiteSeed": 184,
        "blackSeed": 117
      },
      {
        "board": 78,
        "whiteSeed": 120,
        "blackSeed": 180
      },
      {
        "board": 79,
        "whiteSeed": 128,
        "blackSeed": 181
      },
      {
        "board": 80,
        "whiteSeed": 129,
        "blackSeed": 185
      },
      {
        "board": 81,
        "whiteSeed": 130,
        "blackSeed": 187
      },
      {
        "board": 82,
        "whiteSeed": 132,
        "blackSeed": 189
      },
      {
        "board": 83,
        "whiteSeed": 188,
        "blackSeed": 133
      },
      {
        "board": 84,
        "whiteSeed": 194,
        "blackSeed": 135
      },
      {
        "board": 85,
        "whiteSeed": 136,
        "blackSeed": 193
      },
      {
        "board": 86,
        "whiteSeed": 198,
        "blackSeed": 137
      },
      {
        "board": 87,
        "whiteSeed": 215,
        "blackSeed": 139
      },
      {
        "board": 88,
        "whiteSeed": 140,
        "blackSeed": 195
      },
      {
        "board": 89,
        "whiteSeed": 222,
        "blackSeed": 141
      },
      {
        "board": 90,
        "whiteSeed": 142,
        "blackSeed": 197
      },
      {
        "board": 91,
        "whiteSeed": 223,
        "blackSeed": 143
      },
      {
        "board": 92,
        "whiteSeed": 144,
        "blackSeed": 203
      },
      {
        "board": 93,
        "whiteSeed": 146,
        "blackSeed": 205
      },
      {
        "board": 94,
        "whiteSeed": 150,
        "blackSeed": 219
      },
      {
        "board": 95,
        "whiteSeed": 152,
        "blackSeed": 221
      },
      {
        "board": 96,
        "whiteSeed": 226,
        "blackSeed": 155
      },
      {
        "board": 97,
        "whiteSeed": 228,
        "blackSeed": 157
      },
      {
        "board": 98,
        "whiteSeed": 158,
        "blackSeed": 242
      },
      {
        "board": 99,
        "whiteSeed": 232,
        "blackSeed": 159
      },
      {
        "board": 100,
        "whiteSeed": 160,
        "blackSeed": 225
      },
      {
        "board": 101,
        "whiteSeed": 234,
        "blackSeed": 161
      },
      {
        "board": 102,
        "whiteSeed": 162,
        "blackSeed": 245
      },
      {
        "board": 103,
        "whiteSeed": 238,
        "blackSeed": 165
      },
      {
        "board": 104,
        "whiteSeed": 236,
        "blackSeed": 167
      },
      {
        "board": 105,
        "whiteSeed": 168,
        "blackSeed": 247
      },
      {
        "board": 106,
        "whiteSeed": 170,
        "blackSeed": 248
      },
      {
        "board": 107,
        "whiteSeed": 171,
        "blackSeed": 251
      },
      {
        "board": 108,
        "whiteSeed": 172,
        "blackSeed": 253
      },
      {
        "board": 109,
        "whiteSeed": 173,
        "blackSeed": 255
      },
      {
        "board": 110,
        "whiteSeed": 174,
        "blackSeed": 256
      },
      {
        "board": 111,
        "whiteSeed": 254,
        "blackSeed": 207
      },
      {
        "board": 112,
        "whiteSeed": 134,
        "blackSeed": 233
      },
      {
        "board": 113,
        "whiteSeed": 166,
        "blackSeed": 237
      },
      {
        "board": 114,
        "whiteSeed": 218,
        "blackSeed": 190
      },
      {
        "board": 115,
        "whiteSeed": 220,
        "blackSeed": 191
      },
      {
        "board": 116,
        "whiteSeed": 224,
        "blackSeed": 192
      },
      {
        "board": 117,
        "whiteSeed": 196,
        "blackSeed": 229
      },
      {
        "board": 118,
        "whiteSeed": 202,
        "blackSeed": 231
      },
      {
        "board": 119,
        "whiteSeed": 204,
        "blackSeed": 235
      },
      {
        "board": 120,
        "whiteSeed": 206,
        "blackSeed": 239
      },
      {
        "board": 121,
        "whiteSeed": 208,
        "blackSeed": 241
      },
      {
        "board": 122,
        "whiteSeed": 240,
        "blackSeed": 209
      },
      {
        "board": 123,
        "whiteSeed": 244,
        "blackSeed": 210
      },
      {
        "board": 124,
        "whiteSeed": 246,
        "blackSeed": 211
      },
      {
        "board": 125,
        "whiteSeed": 250,
        "blackSeed": 212
      },
      {
        "board": 126,
        "whiteSeed": 216,
        "blackSeed": 243
      },
      {
        "board": 127,
        "whiteSeed": 252,
        "blackSeed": 217
      }
    ]
  },
  {
    "round": 5,
    "pairings": [
      {
        "board": 1,
        "whiteSeed": 70,
        "blackSeed": 2
      },
      {
        "board": 2,
        "whiteSeed": 82,
        "blackSeed": 12
      },
      {
        "board": 3,
        "whiteSeed": 89,
        "blackSeed": 32
      },
      {
        "board": 4,
        "whiteSeed": 43,
        "blackSeed": 94
      },
      {
        "board": 5,
        "whiteSeed": 59,
        "blackSeed": 156
      },
      {
        "board": 6,
        "whiteSeed": 126,
        "blackSeed": 69
      },
      {
        "board": 7,
        "whiteSeed": 7,
        "blackSeed": 72
      },
      {
        "board": 8,
        "whiteSeed": 25,
        "blackSeed": 119
      },
      {
        "board": 9,
        "whiteSeed": 257,
        "blackSeed": 40
      },
      {
        "board": 10,
        "whiteSeed": 1,
        "blackSeed": 54
      },
      {
        "board": 11,
        "whiteSeed": 55,
        "blackSeed": 6
      },
      {
        "board": 12,
        "whiteSeed": 56,
        "blackSeed": 8
      },
      {
        "board": 13,
        "whiteSeed": 9,
        "blackSeed": 57
      },
      {
        "board": 14,
        "whiteSeed": 61,
        "blackSeed": 10
      },
      {
        "board": 15,
        "whiteSeed": 13,
        "blackSeed": 62
      },
      {
        "board": 16,
        "whiteSeed": 63,
        "blackSeed": 14
      },
      {
        "board": 17,
        "whiteSeed": 15,
        "blackSeed": 64
      },
      {
        "board": 18,
        "whiteSeed": 65,
        "blackSeed": 16
      },
      {
        "board": 19,
        "whiteSeed": 19,
        "blackSeed": 66
      },
      {
        "board": 20,
        "whiteSeed": 67,
        "blackSeed": 21
      },
      {
        "board": 21,
        "whiteSeed": 73,
        "blackSeed": 22
      },
      {
        "board": 22,
        "whiteSeed": 27,
        "blackSeed": 68
      },
      {
        "board": 23,
        "whiteSeed": 91,
        "blackSeed": 28
      },
      {
        "board": 24,
        "whiteSeed": 29,
        "blackSeed": 76
      },
      {
        "board": 25,
        "whiteSeed": 93,
        "blackSeed": 30
      },
      {
        "board": 26,
        "whiteSeed": 31,
        "blackSeed": 86
      },
      {
        "board": 27,
        "whiteSeed": 33,
        "blackSeed": 95
      },
      {
        "board": 28,
        "whiteSeed": 37,
        "blackSeed": 109
      },
      {
        "board": 29,
        "whiteSeed": 39,
        "blackSeed": 113
      },
      {
        "board": 30,
        "whiteSeed": 41,
        "blackSeed": 127
      },
      {
        "board": 31,
        "whiteSeed": 115,
        "blackSeed": 44
      },
      {
        "board": 32,
        "whiteSeed": 123,
        "blackSeed": 46
      },
      {
        "board": 33,
        "whiteSeed": 47,
        "blackSeed": 118
      },
      {
        "board": 34,
        "whiteSeed": 124,
        "blackSeed": 52
      },
      {
        "board": 35,
        "whiteSeed": 92,
        "blackSeed": 4
      },
      {
        "board": 36,
        "whiteSeed": 11,
        "blackSeed": 100
      },
      {
        "board": 37,
        "whiteSeed": 17,
        "blackSeed": 108
      },
      {
        "board": 38,
        "whiteSeed": 103,
        "blackSeed": 24
      },
      {
        "board": 39,
        "whiteSeed": 149,
        "blackSeed": 34
      },
      {
        "board": 40,
        "whiteSeed": 35,
        "blackSeed": 112
      },
      {
        "board": 41,
        "whiteSeed": 49,
        "blackSeed": 116
      },
      {
        "board": 42,
        "whiteSeed": 51,
        "blackSeed": 154
      },
      {
        "board": 43,
        "whiteSeed": 131,
        "blackSeed": 60
      },
      {
        "board": 44,
        "whiteSeed": 71,
        "blackSeed": 230
      },
      {
        "board": 45,
        "whiteSeed": 75,
        "blackSeed": 199
      },
      {
        "board": 46,
        "whiteSeed": 151,
        "blackSeed": 80
      },
      {
        "board": 47,
        "whiteSeed": 3,
        "blackSeed": 138
      },
      {
        "board": 48,
        "whiteSeed": 5,
        "blackSeed": 140
      },
      {
        "board": 49,
        "whiteSeed": 18,
        "blackSeed": 142
      },
      {
        "board": 50,
        "whiteSeed": 139,
        "blackSeed": 20
      },
      {
        "board": 51,
        "whiteSeed": 23,
        "blackSeed": 146
      },
      {
        "board": 52,
        "whiteSeed": 157,
        "blackSeed": 26
      },
      {
        "board": 53,
        "whiteSeed": 153,
        "blackSeed": 36
      },
      {
        "board": 54,
        "whiteSeed": 158,
        "blackSeed": 38
      },
      {
        "board": 55,
        "whiteSeed": 161,
        "blackSeed": 48
      },
      {
        "board": 56,
        "whiteSeed": 53,
        "blackSeed": 160
      },
      {
        "board": 57,
        "whiteSeed": 77,
        "blackSeed": 162
      },
      {
        "board": 58,
        "whiteSeed": 79,
        "blackSeed": 170
      },
      {
        "board": 59,
        "whiteSeed": 81,
        "blackSeed": 171
      },
      {
        "board": 60,
        "whiteSeed": 83,
        "blackSeed": 172
      },
      {
        "board": 61,
        "whiteSeed": 163,
        "blackSeed": 84
      },
      {
        "board": 62,
        "whiteSeed": 85,
        "blackSeed": 173
      },
      {
        "board": 63,
        "whiteSeed": 167,
        "blackSeed": 88
      },
      {
        "board": 64,
        "whiteSeed": 175,
        "blackSeed": 90
      },
      {
        "board": 65,
        "whiteSeed": 179,
        "blackSeed": 96
      },
      {
        "board": 66,
        "whiteSeed": 97,
        "blackSeed": 174
      },
      {
        "board": 67,
        "whiteSeed": 99,
        "blackSeed": 178
      },
      {
        "board": 68,
        "whiteSeed": 101,
        "blackSeed": 186
      },
      {
        "board": 69,
        "whiteSeed": 180,
        "blackSeed": 104
      },
      {
        "board": 70,
        "whiteSeed": 105,
        "blackSeed": 198
      },
      {
        "board": 71,
        "whiteSeed": 189,
        "blackSeed": 106
      },
      {
        "board": 72,
        "whiteSeed": 193,
        "blackSeed": 107
      },
      {
        "board": 73,
        "whiteSeed": 203,
        "blackSeed": 110
      },
      {
        "board": 74,
        "whiteSeed": 111,
        "blackSeed": 201
      },
      {
        "board": 75,
        "whiteSeed": 214,
        "blackSeed": 114
      },
      {
        "board": 76,
        "whiteSeed": 117,
        "blackSeed": 222
      },
      {
        "board": 77,
        "whiteSeed": 121,
        "blackSeed": 223
      },
      {
        "board": 78,
        "whiteSeed": 219,
        "blackSeed": 122
      },
      {
        "board": 79,
        "whiteSeed": 125,
        "blackSeed": 226
      },
      {
        "board": 80,
        "whiteSeed": 221,
        "blackSeed": 128
      },
      {
        "board": 81,
        "whiteSeed": 247,
        "blackSeed": 129
      },
      {
        "board": 82,
        "whiteSeed": 249,
        "blackSeed": 130
      },
      {
        "board": 83,
        "whiteSeed": 135,
        "blackSeed": 238
      },
      {
        "board": 84,
        "whiteSeed": 45,
        "blackSeed": 164
      },
      {
        "board": 85,
        "whiteSeed": 227,
        "blackSeed": 74
      },
      {
        "board": 86,
        "whiteSeed": 169,
        "blackSeed": 78
      },
      {
        "board": 87,
        "whiteSeed": 87,
        "blackSeed": 188
      },
      {
        "board": 88,
        "whiteSeed": 207,
        "blackSeed": 98
      },
      {
        "board": 89,
        "whiteSeed": 133,
        "blackSeed": 177
      },
      {
        "board": 90,
        "whiteSeed": 233,
        "blackSeed": 145
      },
      {
        "board": 91,
        "whiteSeed": 147,
        "blackSeed": 232
      },
      {
        "board": 92,
        "whiteSeed": 159,
        "blackSeed": 200
      },
      {
        "board": 93,
        "whiteSeed": 237,
        "blackSeed": 58
      },
      {
        "board": 94,
        "whiteSeed": 202,
        "blackSeed": 102
      },
      {
        "board": 95,
        "whiteSeed": 204,
        "blackSeed": 120
      },
      {
        "board": 96,
        "whiteSeed": 217,
        "blackSeed": 132
      },
      {
        "board": 97,
        "whiteSeed": 205,
        "blackSeed": 136
      },
      {
        "board": 98,
        "whiteSeed": 137,
        "blackSeed": 208
      },
      {
        "board": 99,
        "whiteSeed": 141,
        "blackSeed": 215
      },
      {
        "board": 100,
        "whiteSeed": 143,
        "blackSeed": 220
      },
      {
        "board": 101,
        "whiteSeed": 225,
        "blackSeed": 144
      },
      {
        "board": 102,
        "whiteSeed": 239,
        "blackSeed": 150
      },
      {
        "board": 103,
        "whiteSeed": 242,
        "blackSeed": 152
      },
      {
        "board": 104,
        "whiteSeed": 155,
        "blackSeed": 228
      },
      {
        "board": 105,
        "whiteSeed": 165,
        "blackSeed": 224
      },
      {
        "board": 106,
        "whiteSeed": 243,
        "blackSeed": 168
      },
      {
        "board": 107,
        "whiteSeed": 248,
        "blackSeed": 176
      },
      {
        "board": 108,
        "whiteSeed": 181,
        "blackSeed": 234
      },
      {
        "board": 109,
        "whiteSeed": 245,
        "blackSeed": 182
      },
      {
        "board": 110,
        "whiteSeed": 251,
        "blackSeed": 183
      },
      {
        "board": 111,
        "whiteSeed": 255,
        "blackSeed": 184
      },
      {
        "board": 112,
        "whiteSeed": 185,
        "blackSeed": 236
      },
      {
        "board": 113,
        "whiteSeed": 187,
        "blackSeed": 240
      },
      {
        "board": 114,
        "whiteSeed": 190,
        "blackSeed": 246
      },
      {
        "board": 115,
        "whiteSeed": 253,
        "blackSeed": 194
      },
      {
        "board": 116,
        "whiteSeed": 195,
        "blackSeed": 250
      },
      {
        "board": 117,
        "whiteSeed": 256,
        "blackSeed": 196
      },
      {
        "board": 118,
        "whiteSeed": 197,
        "blackSeed": 254
      },
      {
        "board": 119,
        "whiteSeed": 210,
        "blackSeed": 134
      },
      {
        "board": 120,
        "whiteSeed": 244,
        "blackSeed": 166
      },
      {
        "board": 121,
        "whiteSeed": 191,
        "blackSeed": 216
      },
      {
        "board": 122,
        "whiteSeed": 192,
        "blackSeed": 218
      },
      {
        "board": 123,
        "whiteSeed": 229,
        "blackSeed": 206
      },
      {
        "board": 124,
        "whiteSeed": 209,
        "blackSeed": 231
      },
      {
        "board": 125,
        "whiteSeed": 211,
        "blackSeed": 235
      },
      {
        "board": 126,
        "whiteSeed": 241,
        "blackSeed": 212
      }
    ]
  },
  {
    "round": 6,
    "pairings": [
      {
        "board": 1,
        "whiteSeed": 2,
        "blackSeed": 126
      },
      {
        "board": 2,
        "whiteSeed": 12,
        "blackSeed": 156
      },
      {
        "board": 3,
        "whiteSeed": 40,
        "blackSeed": 7
      },
      {
        "board": 4,
        "whiteSeed": 94,
        "blackSeed": 25
      },
      {
        "board": 5,
        "whiteSeed": 32,
        "blackSeed": 43
      },
      {
        "board": 6,
        "whiteSeed": 1,
        "blackSeed": 89
      },
      {
        "board": 7,
        "whiteSeed": 6,
        "blackSeed": 33
      },
      {
        "board": 8,
        "whiteSeed": 8,
        "blackSeed": 41
      },
      {
        "board": 9,
        "whiteSeed": 52,
        "blackSeed": 9
      },
      {
        "board": 10,
        "whiteSeed": 10,
        "blackSeed": 59
      },
      {
        "board": 11,
        "whiteSeed": 67,
        "blackSeed": 13
      },
      {
        "board": 12,
        "whiteSeed": 14,
        "blackSeed": 69
      },
      {
        "board": 13,
        "whiteSeed": 86,
        "blackSeed": 15
      },
      {
        "board": 14,
        "whiteSeed": 16,
        "blackSeed": 70
      },
      {
        "board": 15,
        "whiteSeed": 68,
        "blackSeed": 19
      },
      {
        "board": 16,
        "whiteSeed": 28,
        "blackSeed": 73
      },
      {
        "board": 17,
        "whiteSeed": 113,
        "blackSeed": 29
      },
      {
        "board": 18,
        "whiteSeed": 30,
        "blackSeed": 82
      },
      {
        "board": 19,
        "whiteSeed": 4,
        "blackSeed": 123
      },
      {
        "board": 20,
        "whiteSeed": 60,
        "blackSeed": 11
      },
      {
        "board": 21,
        "whiteSeed": 71,
        "blackSeed": 17
      },
      {
        "board": 22,
        "whiteSeed": 24,
        "blackSeed": 75
      },
      {
        "board": 23,
        "whiteSeed": 72,
        "blackSeed": 35
      },
      {
        "board": 24,
        "whiteSeed": 80,
        "blackSeed": 37
      },
      {
        "board": 25,
        "whiteSeed": 44,
        "blackSeed": 257
      },
      {
        "board": 26,
        "whiteSeed": 109,
        "blackSeed": 47
      },
      {
        "board": 27,
        "whiteSeed": 119,
        "blackSeed": 49
      },
      {
        "board": 28,
        "whiteSeed": 118,
        "blackSeed": 51
      },
      {
        "board": 29,
        "whiteSeed": 21,
        "blackSeed": 115
      },
      {
        "board": 30,
        "whiteSeed": 88,
        "blackSeed": 3
      },
      {
        "board": 31,
        "whiteSeed": 90,
        "blackSeed": 5
      },
      {
        "board": 32,
        "whiteSeed": 95,
        "blackSeed": 18
      },
      {
        "board": 33,
        "whiteSeed": 22,
        "blackSeed": 91
      },
      {
        "board": 34,
        "whiteSeed": 96,
        "blackSeed": 23
      },
      {
        "board": 35,
        "whiteSeed": 26,
        "blackSeed": 93
      },
      {
        "board": 36,
        "whiteSeed": 104,
        "blackSeed": 27
      },
      {
        "board": 37,
        "whiteSeed": 110,
        "blackSeed": 31
      },
      {
        "board": 38,
        "whiteSeed": 34,
        "blackSeed": 99
      },
      {
        "board": 39,
        "whiteSeed": 36,
        "blackSeed": 105
      },
      {
        "board": 40,
        "whiteSeed": 38,
        "blackSeed": 111
      },
      {
        "board": 41,
        "whiteSeed": 46,
        "blackSeed": 125
      },
      {
        "board": 42,
        "whiteSeed": 48,
        "blackSeed": 124
      },
      {
        "board": 43,
        "whiteSeed": 114,
        "blackSeed": 53
      },
      {
        "board": 44,
        "whiteSeed": 54,
        "blackSeed": 149
      },
      {
        "board": 45,
        "whiteSeed": 122,
        "blackSeed": 55
      },
      {
        "board": 46,
        "whiteSeed": 129,
        "blackSeed": 56
      },
      {
        "board": 47,
        "whiteSeed": 57,
        "blackSeed": 127
      },
      {
        "board": 48,
        "whiteSeed": 173,
        "blackSeed": 61
      },
      {
        "board": 49,
        "whiteSeed": 62,
        "blackSeed": 193
      },
      {
        "board": 50,
        "whiteSeed": 174,
        "blackSeed": 63
      },
      {
        "board": 51,
        "whiteSeed": 64,
        "blackSeed": 189
      },
      {
        "board": 52,
        "whiteSeed": 66,
        "blackSeed": 221
      },
      {
        "board": 53,
        "whiteSeed": 76,
        "blackSeed": 249
      },
      {
        "board": 54,
        "whiteSeed": 186,
        "blackSeed": 77
      },
      {
        "board": 55,
        "whiteSeed": 222,
        "blackSeed": 79
      },
      {
        "board": 56,
        "whiteSeed": 223,
        "blackSeed": 81
      },
      {
        "board": 57,
        "whiteSeed": 238,
        "blackSeed": 83
      },
      {
        "board": 58,
        "whiteSeed": 20,
        "blackSeed": 151
      },
      {
        "board": 59,
        "whiteSeed": 177,
        "blackSeed": 45
      },
      {
        "board": 60,
        "whiteSeed": 84,
        "blackSeed": 139
      },
      {
        "board": 61,
        "whiteSeed": 145,
        "blackSeed": 87
      },
      {
        "board": 62,
        "whiteSeed": 154,
        "blackSeed": 92
      },
      {
        "board": 63,
        "whiteSeed": 98,
        "blackSeed": 147
      },
      {
        "board": 64,
        "whiteSeed": 100,
        "blackSeed": 169
      },
      {
        "board": 65,
        "whiteSeed": 230,
        "blackSeed": 103
      },
      {
        "board": 66,
        "whiteSeed": 108,
        "blackSeed": 163
      },
      {
        "board": 67,
        "whiteSeed": 112,
        "blackSeed": 227
      },
      {
        "board": 68,
        "whiteSeed": 116,
        "blackSeed": 237
      },
      {
        "board": 69,
        "whiteSeed": 200,
        "blackSeed": 131
      },
      {
        "board": 70,
        "whiteSeed": 199,
        "blackSeed": 85
      },
      {
        "board": 71,
        "whiteSeed": 168,
        "blackSeed": 97
      },
      {
        "board": 72,
        "whiteSeed": 170,
        "blackSeed": 101
      },
      {
        "board": 73,
        "whiteSeed": 102,
        "blackSeed": 167
      },
      {
        "board": 74,
        "whiteSeed": 106,
        "blackSeed": 175
      },
      {
        "board": 75,
        "whiteSeed": 107,
        "blackSeed": 179
      },
      {
        "board": 76,
        "whiteSeed": 171,
        "blackSeed": 117
      },
      {
        "board": 77,
        "whiteSeed": 120,
        "blackSeed": 181
      },
      {
        "board": 78,
        "whiteSeed": 172,
        "blackSeed": 121
      },
      {
        "board": 79,
        "whiteSeed": 128,
        "blackSeed": 180
      },
      {
        "board": 80,
        "whiteSeed": 130,
        "blackSeed": 197
      },
      {
        "board": 81,
        "whiteSeed": 132,
        "blackSeed": 187
      },
      {
        "board": 82,
        "whiteSeed": 176,
        "blackSeed": 135
      },
      {
        "board": 83,
        "whiteSeed": 136,
        "blackSeed": 203
      },
      {
        "board": 84,
        "whiteSeed": 178,
        "blackSeed": 137
      },
      {
        "board": 85,
        "whiteSeed": 138,
        "blackSeed": 214
      },
      {
        "board": 86,
        "whiteSeed": 140,
        "blackSeed": 219
      },
      {
        "board": 87,
        "whiteSeed": 183,
        "blackSeed": 141
      },
      {
        "board": 88,
        "whiteSeed": 142,
        "blackSeed": 225
      },
      {
        "board": 89,
        "whiteSeed": 196,
        "blackSeed": 143
      },
      {
        "board": 90,
        "whiteSeed": 146,
        "blackSeed": 242
      },
      {
        "board": 91,
        "whiteSeed": 150,
        "blackSeed": 245
      },
      {
        "board": 92,
        "whiteSeed": 198,
        "blackSeed": 153
      },
      {
        "board": 93,
        "whiteSeed": 201,
        "blackSeed": 155
      },
      {
        "board": 94,
        "whiteSeed": 236,
        "blackSeed": 157
      },
      {
        "board": 95,
        "whiteSeed": 226,
        "blackSeed": 158
      },
      {
        "board": 96,
        "whiteSeed": 160,
        "blackSeed": 247
      },
      {
        "board": 97,
        "whiteSeed": 246,
        "blackSeed": 161
      },
      {
        "board": 98,
        "whiteSeed": 162,
        "blackSeed": 253
      },
      {
        "board": 99,
        "whiteSeed": 250,
        "blackSeed": 165
      },
      {
        "board": 100,
        "whiteSeed": 74,
        "blackSeed": 255
      },
      {
        "board": 101,
        "whiteSeed": 232,
        "blackSeed": 133
      },
      {
        "board": 102,
        "whiteSeed": 134,
        "blackSeed": 159
      },
      {
        "board": 103,
        "whiteSeed": 164,
        "blackSeed": 207
      },
      {
        "board": 104,
        "whiteSeed": 166,
        "blackSeed": 233
      },
      {
        "board": 105,
        "whiteSeed": 188,
        "blackSeed": 144
      },
      {
        "board": 106,
        "whiteSeed": 58,
        "blackSeed": 216
      },
      {
        "board": 107,
        "whiteSeed": 152,
        "blackSeed": 218
      },
      {
        "board": 108,
        "whiteSeed": 182,
        "blackSeed": 217
      },
      {
        "board": 109,
        "whiteSeed": 184,
        "blackSeed": 239
      },
      {
        "board": 110,
        "whiteSeed": 220,
        "blackSeed": 185
      },
      {
        "board": 111,
        "whiteSeed": 190,
        "blackSeed": 241
      },
      {
        "board": 112,
        "whiteSeed": 194,
        "blackSeed": 243
      },
      {
        "board": 113,
        "whiteSeed": 228,
        "blackSeed": 195
      },
      {
        "board": 114,
        "whiteSeed": 234,
        "blackSeed": 202
      },
      {
        "board": 115,
        "whiteSeed": 231,
        "blackSeed": 204
      },
      {
        "board": 116,
        "whiteSeed": 240,
        "blackSeed": 205
      },
      {
        "board": 117,
        "whiteSeed": 206,
        "blackSeed": 248
      },
      {
        "board": 118,
        "whiteSeed": 208,
        "blackSeed": 251
      },
      {
        "board": 119,
        "whiteSeed": 254,
        "blackSeed": 211
      },
      {
        "board": 120,
        "whiteSeed": 215,
        "blackSeed": 256
      },
      {
        "board": 121,
        "whiteSeed": 191,
        "blackSeed": 210
      },
      {
        "board": 122,
        "whiteSeed": 192,
        "blackSeed": 244
      },
      {
        "board": 123,
        "whiteSeed": 235,
        "blackSeed": 209
      },
      {
        "board": 124,
        "whiteSeed": 212,
        "blackSeed": 229
      }
    ]
  },
  {
    "round": 7,
    "pairings": [
      {
        "board": 1,
        "whiteSeed": 12,
        "blackSeed": 2
      },
      {
        "board": 2,
        "whiteSeed": 156,
        "blackSeed": 32
      },
      {
        "board": 3,
        "whiteSeed": 7,
        "blackSeed": 94
      },
      {
        "board": 4,
        "whiteSeed": 9,
        "blackSeed": 41
      },
      {
        "board": 5,
        "whiteSeed": 59,
        "blackSeed": 14
      },
      {
        "board": 6,
        "whiteSeed": 15,
        "blackSeed": 67
      },
      {
        "board": 7,
        "whiteSeed": 19,
        "blackSeed": 73
      },
      {
        "board": 8,
        "whiteSeed": 33,
        "blackSeed": 89
      },
      {
        "board": 9,
        "whiteSeed": 123,
        "blackSeed": 40
      },
      {
        "board": 10,
        "whiteSeed": 126,
        "blackSeed": 16
      },
      {
        "board": 11,
        "whiteSeed": 43,
        "blackSeed": 1
      },
      {
        "board": 12,
        "whiteSeed": 17,
        "blackSeed": 60
      },
      {
        "board": 13,
        "whiteSeed": 70,
        "blackSeed": 24
      },
      {
        "board": 14,
        "whiteSeed": 25,
        "blackSeed": 82
      },
      {
        "board": 15,
        "whiteSeed": 29,
        "blackSeed": 119
      },
      {
        "board": 16,
        "whiteSeed": 115,
        "blackSeed": 30
      },
      {
        "board": 17,
        "whiteSeed": 37,
        "blackSeed": 113
      },
      {
        "board": 18,
        "whiteSeed": 257,
        "blackSeed": 6
      },
      {
        "board": 19,
        "whiteSeed": 5,
        "blackSeed": 62
      },
      {
        "board": 20,
        "whiteSeed": 64,
        "blackSeed": 8
      },
      {
        "board": 21,
        "whiteSeed": 69,
        "blackSeed": 10
      },
      {
        "board": 22,
        "whiteSeed": 13,
        "blackSeed": 68
      },
      {
        "board": 23,
        "whiteSeed": 77,
        "blackSeed": 22
      },
      {
        "board": 24,
        "whiteSeed": 23,
        "blackSeed": 66
      },
      {
        "board": 25,
        "whiteSeed": 79,
        "blackSeed": 26
      },
      {
        "board": 26,
        "whiteSeed": 27,
        "blackSeed": 72
      },
      {
        "board": 27,
        "whiteSeed": 83,
        "blackSeed": 28
      },
      {
        "board": 28,
        "whiteSeed": 31,
        "blackSeed": 109
      },
      {
        "board": 29,
        "whiteSeed": 111,
        "blackSeed": 34
      },
      {
        "board": 30,
        "whiteSeed": 35,
        "blackSeed": 86
      },
      {
        "board": 31,
        "whiteSeed": 105,
        "blackSeed": 46
      },
      {
        "board": 32,
        "whiteSeed": 47,
        "blackSeed": 129
      },
      {
        "board": 33,
        "whiteSeed": 127,
        "blackSeed": 48
      },
      {
        "board": 34,
        "whiteSeed": 51,
        "blackSeed": 173
      },
      {
        "board": 35,
        "whiteSeed": 174,
        "blackSeed": 52
      },
      {
        "board": 36,
        "whiteSeed": 55,
        "blackSeed": 118
      },
      {
        "board": 37,
        "whiteSeed": 3,
        "blackSeed": 223
      },
      {
        "board": 38,
        "whiteSeed": 87,
        "blackSeed": 4
      },
      {
        "board": 39,
        "whiteSeed": 11,
        "blackSeed": 88
      },
      {
        "board": 40,
        "whiteSeed": 98,
        "blackSeed": 44
      },
      {
        "board": 41,
        "whiteSeed": 49,
        "blackSeed": 108
      },
      {
        "board": 42,
        "whiteSeed": 53,
        "blackSeed": 112
      },
      {
        "board": 43,
        "whiteSeed": 131,
        "blackSeed": 54
      },
      {
        "board": 44,
        "whiteSeed": 149,
        "blackSeed": 71
      },
      {
        "board": 45,
        "whiteSeed": 75,
        "blackSeed": 114
      },
      {
        "board": 46,
        "whiteSeed": 151,
        "blackSeed": 76
      },
      {
        "board": 47,
        "whiteSeed": 249,
        "blackSeed": 80
      },
      {
        "board": 48,
        "whiteSeed": 45,
        "blackSeed": 116
      },
      {
        "board": 49,
        "whiteSeed": 139,
        "blackSeed": 21
      },
      {
        "board": 50,
        "whiteSeed": 141,
        "blackSeed": 36
      },
      {
        "board": 51,
        "whiteSeed": 143,
        "blackSeed": 38
      },
      {
        "board": 52,
        "whiteSeed": 56,
        "blackSeed": 136
      },
      {
        "board": 53,
        "whiteSeed": 157,
        "blackSeed": 57
      },
      {
        "board": 54,
        "whiteSeed": 61,
        "blackSeed": 140
      },
      {
        "board": 55,
        "whiteSeed": 81,
        "blackSeed": 154
      },
      {
        "board": 56,
        "whiteSeed": 161,
        "blackSeed": 84
      },
      {
        "board": 57,
        "whiteSeed": 169,
        "blackSeed": 85
      },
      {
        "board": 58,
        "whiteSeed": 189,
        "blackSeed": 90
      },
      {
        "board": 59,
        "whiteSeed": 91,
        "blackSeed": 162
      },
      {
        "board": 60,
        "whiteSeed": 92,
        "blackSeed": 170
      },
      {
        "board": 61,
        "whiteSeed": 93,
        "blackSeed": 171
      },
      {
        "board": 62,
        "whiteSeed": 175,
        "blackSeed": 95
      },
      {
        "board": 63,
        "whiteSeed": 193,
        "blackSeed": 96
      },
      {
        "board": 64,
        "whiteSeed": 97,
        "blackSeed": 177
      },
      {
        "board": 65,
        "whiteSeed": 99,
        "blackSeed": 186
      },
      {
        "board": 66,
        "whiteSeed": 198,
        "blackSeed": 100
      },
      {
        "board": 67,
        "whiteSeed": 103,
        "blackSeed": 222
      },
      {
        "board": 68,
        "whiteSeed": 214,
        "blackSeed": 104
      },
      {
        "board": 69,
        "whiteSeed": 221,
        "blackSeed": 110
      },
      {
        "board": 70,
        "whiteSeed": 225,
        "blackSeed": 122
      },
      {
        "board": 71,
        "whiteSeed": 124,
        "blackSeed": 226
      },
      {
        "board": 72,
        "whiteSeed": 125,
        "blackSeed": 230
      },
      {
        "board": 73,
        "whiteSeed": 242,
        "blackSeed": 128
      },
      {
        "board": 74,
        "whiteSeed": 245,
        "blackSeed": 130
      },
      {
        "board": 75,
        "whiteSeed": 247,
        "blackSeed": 132
      },
      {
        "board": 76,
        "whiteSeed": 121,
        "blackSeed": 238
      },
      {
        "board": 77,
        "whiteSeed": 167,
        "blackSeed": 20
      },
      {
        "board": 78,
        "whiteSeed": 181,
        "blackSeed": 102
      },
      {
        "board": 79,
        "whiteSeed": 227,
        "blackSeed": 107
      },
      {
        "board": 80,
        "whiteSeed": 179,
        "blackSeed": 120
      },
      {
        "board": 81,
        "whiteSeed": 133,
        "blackSeed": 166
      },
      {
        "board": 82,
        "whiteSeed": 237,
        "blackSeed": 134
      },
      {
        "board": 83,
        "whiteSeed": 135,
        "blackSeed": 172
      },
      {
        "board": 84,
        "whiteSeed": 137,
        "blackSeed": 176
      },
      {
        "board": 85,
        "whiteSeed": 255,
        "blackSeed": 145
      },
      {
        "board": 86,
        "whiteSeed": 147,
        "blackSeed": 178
      },
      {
        "board": 87,
        "whiteSeed": 155,
        "blackSeed": 200
      },
      {
        "board": 88,
        "whiteSeed": 163,
        "blackSeed": 250
      },
      {
        "board": 89,
        "whiteSeed": 165,
        "blackSeed": 201
      },
      {
        "board": 90,
        "whiteSeed": 195,
        "blackSeed": 74
      },
      {
        "board": 91,
        "whiteSeed": 101,
        "blackSeed": 190
      },
      {
        "board": 92,
        "whiteSeed": 197,
        "blackSeed": 106
      },
      {
        "board": 93,
        "whiteSeed": 117,
        "blackSeed": 196
      },
      {
        "board": 94,
        "whiteSeed": 202,
        "blackSeed": 138
      },
      {
        "board": 95,
        "whiteSeed": 203,
        "blackSeed": 142
      },
      {
        "board": 96,
        "whiteSeed": 144,
        "blackSeed": 205
      },
      {
        "board": 97,
        "whiteSeed": 207,
        "blackSeed": 146
      },
      {
        "board": 98,
        "whiteSeed": 215,
        "blackSeed": 150
      },
      {
        "board": 99,
        "whiteSeed": 216,
        "blackSeed": 152
      },
      {
        "board": 100,
        "whiteSeed": 219,
        "blackSeed": 158
      },
      {
        "board": 101,
        "whiteSeed": 243,
        "blackSeed": 160
      },
      {
        "board": 102,
        "whiteSeed": 248,
        "blackSeed": 164
      },
      {
        "board": 103,
        "whiteSeed": 251,
        "blackSeed": 168
      },
      {
        "board": 104,
        "whiteSeed": 180,
        "blackSeed": 231
      },
      {
        "board": 105,
        "whiteSeed": 182,
        "blackSeed": 236
      },
      {
        "board": 106,
        "whiteSeed": 253,
        "blackSeed": 183
      },
      {
        "board": 107,
        "whiteSeed": 185,
        "blackSeed": 246
      },
      {
        "board": 108,
        "whiteSeed": 187,
        "blackSeed": 254
      },
      {
        "board": 109,
        "whiteSeed": 159,
        "blackSeed": 188
      },
      {
        "board": 110,
        "whiteSeed": 233,
        "blackSeed": 184
      },
      {
        "board": 111,
        "whiteSeed": 244,
        "blackSeed": 232
      },
      {
        "board": 112,
        "whiteSeed": 239,
        "blackSeed": 194
      },
      {
        "board": 113,
        "whiteSeed": 218,
        "blackSeed": 191
      },
      {
        "board": 114,
        "whiteSeed": 204,
        "blackSeed": 220
      },
      {
        "board": 115,
        "whiteSeed": 241,
        "blackSeed": 206
      },
      {
        "board": 116,
        "whiteSeed": 224,
        "blackSeed": 208
      },
      {
        "board": 117,
        "whiteSeed": 211,
        "blackSeed": 228
      },
      {
        "board": 118,
        "whiteSeed": 212,
        "blackSeed": 234
      },
      {
        "board": 119,
        "whiteSeed": 235,
        "blackSeed": 240
      },
      {
        "board": 120,
        "whiteSeed": 209,
        "blackSeed": 210
      },
      {
        "board": 121,
        "whiteSeed": 229,
        "blackSeed": 192
      }
    ]
  },
  {
    "round": 8,
    "pairings": [
      {
        "board": 1,
        "whiteSeed": 94,
        "blackSeed": 12
      },
      {
        "board": 2,
        "whiteSeed": 2,
        "blackSeed": 156
      },
      {
        "board": 3,
        "whiteSeed": 73,
        "blackSeed": 14
      },
      {
        "board": 4,
        "whiteSeed": 89,
        "blackSeed": 15
      },
      {
        "board": 5,
        "whiteSeed": 41,
        "blackSeed": 123
      },
      {
        "board": 6,
        "whiteSeed": 113,
        "blackSeed": 1
      },
      {
        "board": 7,
        "whiteSeed": 16,
        "blackSeed": 82
      },
      {
        "board": 8,
        "whiteSeed": 119,
        "blackSeed": 17
      },
      {
        "board": 9,
        "whiteSeed": 32,
        "blackSeed": 115
      },
      {
        "board": 10,
        "whiteSeed": 46,
        "blackSeed": 5
      },
      {
        "board": 11,
        "whiteSeed": 6,
        "blackSeed": 47
      },
      {
        "board": 12,
        "whiteSeed": 48,
        "blackSeed": 7
      },
      {
        "board": 13,
        "whiteSeed": 8,
        "blackSeed": 51
      },
      {
        "board": 14,
        "whiteSeed": 59,
        "blackSeed": 9
      },
      {
        "board": 15,
        "whiteSeed": 52,
        "blackSeed": 19
      },
      {
        "board": 16,
        "whiteSeed": 67,
        "blackSeed": 23
      },
      {
        "board": 17,
        "whiteSeed": 24,
        "blackSeed": 69
      },
      {
        "board": 18,
        "whiteSeed": 109,
        "blackSeed": 27
      },
      {
        "board": 19,
        "whiteSeed": 28,
        "blackSeed": 70
      },
      {
        "board": 20,
        "whiteSeed": 68,
        "blackSeed": 33
      },
      {
        "board": 21,
        "whiteSeed": 34,
        "blackSeed": 77
      },
      {
        "board": 22,
        "whiteSeed": 118,
        "blackSeed": 35
      },
      {
        "board": 23,
        "whiteSeed": 40,
        "blackSeed": 126
      },
      {
        "board": 24,
        "whiteSeed": 53,
        "blackSeed": 3
      },
      {
        "board": 25,
        "whiteSeed": 4,
        "blackSeed": 79
      },
      {
        "board": 26,
        "whiteSeed": 54,
        "blackSeed": 11
      },
      {
        "board": 27,
        "whiteSeed": 26,
        "blackSeed": 149
      },
      {
        "board": 28,
        "whiteSeed": 60,
        "blackSeed": 29
      },
      {
        "board": 29,
        "whiteSeed": 30,
        "blackSeed": 249
      },
      {
        "board": 30,
        "whiteSeed": 76,
        "blackSeed": 37
      },
      {
        "board": 31,
        "whiteSeed": 114,
        "blackSeed": 43
      },
      {
        "board": 32,
        "whiteSeed": 257,
        "blackSeed": 49
      },
      {
        "board": 33,
        "whiteSeed": 10,
        "blackSeed": 99
      },
      {
        "board": 34,
        "whiteSeed": 100,
        "blackSeed": 13
      },
      {
        "board": 35,
        "whiteSeed": 21,
        "blackSeed": 105
      },
      {
        "board": 36,
        "whiteSeed": 116,
        "blackSeed": 31
      },
      {
        "board": 37,
        "whiteSeed": 36,
        "blackSeed": 111
      },
      {
        "board": 38,
        "whiteSeed": 44,
        "blackSeed": 124
      },
      {
        "board": 39,
        "whiteSeed": 110,
        "blackSeed": 55
      },
      {
        "board": 40,
        "whiteSeed": 130,
        "blackSeed": 56
      },
      {
        "board": 41,
        "whiteSeed": 122,
        "blackSeed": 61
      },
      {
        "board": 42,
        "whiteSeed": 62,
        "blackSeed": 127
      },
      {
        "board": 43,
        "whiteSeed": 129,
        "blackSeed": 64
      },
      {
        "board": 44,
        "whiteSeed": 66,
        "blackSeed": 143
      },
      {
        "board": 45,
        "whiteSeed": 72,
        "blackSeed": 169
      },
      {
        "board": 46,
        "whiteSeed": 157,
        "blackSeed": 81
      },
      {
        "board": 47,
        "whiteSeed": 173,
        "blackSeed": 83
      },
      {
        "board": 48,
        "whiteSeed": 84,
        "blackSeed": 193
      },
      {
        "board": 49,
        "whiteSeed": 86,
        "blackSeed": 175
      },
      {
        "board": 50,
        "whiteSeed": 90,
        "blackSeed": 214
      },
      {
        "board": 51,
        "whiteSeed": 174,
        "blackSeed": 91
      },
      {
        "board": 52,
        "whiteSeed": 223,
        "blackSeed": 92
      },
      {
        "board": 53,
        "whiteSeed": 230,
        "blackSeed": 93
      },
      {
        "board": 54,
        "whiteSeed": 242,
        "blackSeed": 98
      },
      {
        "board": 55,
        "whiteSeed": 71,
        "blackSeed": 247
      },
      {
        "board": 56,
        "whiteSeed": 135,
        "blackSeed": 45
      },
      {
        "board": 57,
        "whiteSeed": 80,
        "blackSeed": 147
      },
      {
        "board": 58,
        "whiteSeed": 151,
        "blackSeed": 87
      },
      {
        "board": 59,
        "whiteSeed": 88,
        "blackSeed": 155
      },
      {
        "board": 60,
        "whiteSeed": 163,
        "blackSeed": 97
      },
      {
        "board": 61,
        "whiteSeed": 177,
        "blackSeed": 103
      },
      {
        "board": 62,
        "whiteSeed": 108,
        "blackSeed": 167
      },
      {
        "board": 63,
        "whiteSeed": 112,
        "blackSeed": 179
      },
      {
        "board": 64,
        "whiteSeed": 222,
        "blackSeed": 131
      },
      {
        "board": 65,
        "whiteSeed": 238,
        "blackSeed": 133
      },
      {
        "board": 66,
        "whiteSeed": 134,
        "blackSeed": 255
      },
      {
        "board": 67,
        "whiteSeed": 38,
        "blackSeed": 227
      },
      {
        "board": 68,
        "whiteSeed": 162,
        "blackSeed": 85
      },
      {
        "board": 69,
        "whiteSeed": 170,
        "blackSeed": 95
      },
      {
        "board": 70,
        "whiteSeed": 96,
        "blackSeed": 161
      },
      {
        "board": 71,
        "whiteSeed": 102,
        "blackSeed": 165
      },
      {
        "board": 72,
        "whiteSeed": 104,
        "blackSeed": 181
      },
      {
        "board": 73,
        "whiteSeed": 106,
        "blackSeed": 182
      },
      {
        "board": 74,
        "whiteSeed": 176,
        "blackSeed": 117
      },
      {
        "board": 75,
        "whiteSeed": 171,
        "blackSeed": 121
      },
      {
        "board": 76,
        "whiteSeed": 186,
        "blackSeed": 125
      },
      {
        "board": 77,
        "whiteSeed": 128,
        "blackSeed": 187
      },
      {
        "board": 78,
        "whiteSeed": 132,
        "blackSeed": 195
      },
      {
        "board": 79,
        "whiteSeed": 136,
        "blackSeed": 189
      },
      {
        "board": 80,
        "whiteSeed": 190,
        "blackSeed": 137
      },
      {
        "board": 81,
        "whiteSeed": 138,
        "blackSeed": 198
      },
      {
        "board": 82,
        "whiteSeed": 226,
        "blackSeed": 139
      },
      {
        "board": 83,
        "whiteSeed": 140,
        "blackSeed": 201
      },
      {
        "board": 84,
        "whiteSeed": 231,
        "blackSeed": 141
      },
      {
        "board": 85,
        "whiteSeed": 142,
        "blackSeed": 215
      },
      {
        "board": 86,
        "whiteSeed": 146,
        "blackSeed": 225
      },
      {
        "board": 87,
        "whiteSeed": 152,
        "blackSeed": 245
      },
      {
        "board": 88,
        "whiteSeed": 154,
        "blackSeed": 221
      },
      {
        "board": 89,
        "whiteSeed": 158,
        "blackSeed": 248
      },
      {
        "board": 90,
        "whiteSeed": 160,
        "blackSeed": 253
      },
      {
        "board": 91,
        "whiteSeed": 246,
        "blackSeed": 20
      },
      {
        "board": 92,
        "whiteSeed": 184,
        "blackSeed": 107
      },
      {
        "board": 93,
        "whiteSeed": 120,
        "blackSeed": 188
      },
      {
        "board": 94,
        "whiteSeed": 200,
        "blackSeed": 144
      },
      {
        "board": 95,
        "whiteSeed": 205,
        "blackSeed": 145
      },
      {
        "board": 96,
        "whiteSeed": 166,
        "blackSeed": 232
      },
      {
        "board": 97,
        "whiteSeed": 168,
        "blackSeed": 237
      },
      {
        "board": 98,
        "whiteSeed": 172,
        "blackSeed": 239
      },
      {
        "board": 99,
        "whiteSeed": 178,
        "blackSeed": 251
      },
      {
        "board": 100,
        "whiteSeed": 250,
        "blackSeed": 101
      },
      {
        "board": 101,
        "whiteSeed": 150,
        "blackSeed": 207
      },
      {
        "board": 102,
        "whiteSeed": 164,
        "blackSeed": 216
      },
      {
        "board": 103,
        "whiteSeed": 206,
        "blackSeed": 180
      },
      {
        "board": 104,
        "whiteSeed": 183,
        "blackSeed": 224
      },
      {
        "board": 105,
        "whiteSeed": 218,
        "blackSeed": 185
      },
      {
        "board": 106,
        "whiteSeed": 196,
        "blackSeed": 243
      },
      {
        "board": 107,
        "whiteSeed": 228,
        "blackSeed": 197
      },
      {
        "board": 108,
        "whiteSeed": 236,
        "blackSeed": 202
      },
      {
        "board": 109,
        "whiteSeed": 234,
        "blackSeed": 203
      },
      {
        "board": 110,
        "whiteSeed": 240,
        "blackSeed": 204
      },
      {
        "board": 111,
        "whiteSeed": 254,
        "blackSeed": 244
      },
      {
        "board": 112,
        "whiteSeed": 210,
        "blackSeed": 159
      },
      {
        "board": 113,
        "whiteSeed": 208,
        "blackSeed": 233
      },
      {
        "board": 114,
        "whiteSeed": 191,
        "blackSeed": 212
      },
      {
        "board": 115,
        "whiteSeed": 192,
        "blackSeed": 241
      },
      {
        "board": 116,
        "whiteSeed": 220,
        "blackSeed": 211
      },
      {
        "board": 117,
        "whiteSeed": 229,
        "blackSeed": 209
      },
      {
        "board": 118,
        "whiteSeed": 235,
        "blackSeed": null
      }
    ]
  },
  {
    "round": 9,
    "pairings": [
      {
        "board": 1,
        "whiteSeed": 156,
        "blackSeed": 94
      },
      {
        "board": 2,
        "whiteSeed": 14,
        "blackSeed": 12
      },
      {
        "board": 3,
        "whiteSeed": 123,
        "blackSeed": 89
      },
      {
        "board": 4,
        "whiteSeed": 1,
        "blackSeed": 16
      },
      {
        "board": 5,
        "whiteSeed": 15,
        "blackSeed": 119
      },
      {
        "board": 6,
        "whiteSeed": 115,
        "blackSeed": 24
      },
      {
        "board": 7,
        "whiteSeed": 2,
        "blackSeed": 35
      },
      {
        "board": 8,
        "whiteSeed": 70,
        "blackSeed": 6
      },
      {
        "board": 9,
        "whiteSeed": 7,
        "blackSeed": 41
      },
      {
        "board": 10,
        "whiteSeed": 9,
        "blackSeed": 40
      },
      {
        "board": 11,
        "whiteSeed": 19,
        "blackSeed": 46
      },
      {
        "board": 12,
        "whiteSeed": 27,
        "blackSeed": 67
      },
      {
        "board": 13,
        "whiteSeed": 33,
        "blackSeed": 73
      },
      {
        "board": 14,
        "whiteSeed": 3,
        "blackSeed": 43
      },
      {
        "board": 15,
        "whiteSeed": 49,
        "blackSeed": 8
      },
      {
        "board": 16,
        "whiteSeed": 17,
        "blackSeed": 113
      },
      {
        "board": 17,
        "whiteSeed": 51,
        "blackSeed": 30
      },
      {
        "board": 18,
        "whiteSeed": 77,
        "blackSeed": 32
      },
      {
        "board": 19,
        "whiteSeed": 82,
        "blackSeed": 34
      },
      {
        "board": 20,
        "whiteSeed": 37,
        "blackSeed": 54
      },
      {
        "board": 21,
        "whiteSeed": 79,
        "blackSeed": 5
      },
      {
        "board": 22,
        "whiteSeed": 13,
        "blackSeed": 109
      },
      {
        "board": 23,
        "whiteSeed": 23,
        "blackSeed": 84
      },
      {
        "board": 24,
        "whiteSeed": 83,
        "blackSeed": 26
      },
      {
        "board": 25,
        "whiteSeed": 93,
        "blackSeed": 28
      },
      {
        "board": 26,
        "whiteSeed": 29,
        "blackSeed": 110
      },
      {
        "board": 27,
        "whiteSeed": 91,
        "blackSeed": 36
      },
      {
        "board": 28,
        "whiteSeed": 99,
        "blackSeed": 44
      },
      {
        "board": 29,
        "whiteSeed": 47,
        "blackSeed": 127
      },
      {
        "board": 30,
        "whiteSeed": 98,
        "blackSeed": 48
      },
      {
        "board": 31,
        "whiteSeed": 105,
        "blackSeed": 59
      },
      {
        "board": 32,
        "whiteSeed": 126,
        "blackSeed": 60
      },
      {
        "board": 33,
        "whiteSeed": 61,
        "blackSeed": 116
      },
      {
        "board": 34,
        "whiteSeed": 64,
        "blackSeed": 130
      },
      {
        "board": 35,
        "whiteSeed": 149,
        "blackSeed": 66
      },
      {
        "board": 36,
        "whiteSeed": 223,
        "blackSeed": 68
      },
      {
        "board": 37,
        "whiteSeed": 69,
        "blackSeed": 157
      },
      {
        "board": 38,
        "whiteSeed": 247,
        "blackSeed": 72
      },
      {
        "board": 39,
        "whiteSeed": 103,
        "blackSeed": 4
      },
      {
        "board": 40,
        "whiteSeed": 11,
        "blackSeed": 114
      },
      {
        "board": 41,
        "whiteSeed": 134,
        "blackSeed": 53
      },
      {
        "board": 42,
        "whiteSeed": 167,
        "blackSeed": 76
      },
      {
        "board": 43,
        "whiteSeed": 175,
        "blackSeed": 80
      },
      {
        "board": 44,
        "whiteSeed": 249,
        "blackSeed": 86
      },
      {
        "board": 45,
        "whiteSeed": 214,
        "blackSeed": 88
      },
      {
        "board": 46,
        "whiteSeed": 179,
        "blackSeed": 90
      },
      {
        "board": 47,
        "whiteSeed": 97,
        "blackSeed": 257
      },
      {
        "board": 48,
        "whiteSeed": 31,
        "blackSeed": 151
      },
      {
        "board": 49,
        "whiteSeed": 141,
        "blackSeed": 10
      },
      {
        "board": 50,
        "whiteSeed": 143,
        "blackSeed": 21
      },
      {
        "board": 51,
        "whiteSeed": 38,
        "blackSeed": 140
      },
      {
        "board": 52,
        "whiteSeed": 45,
        "blackSeed": 142
      },
      {
        "board": 53,
        "whiteSeed": 55,
        "blackSeed": 161
      },
      {
        "board": 54,
        "whiteSeed": 169,
        "blackSeed": 56
      },
      {
        "board": 55,
        "whiteSeed": 85,
        "blackSeed": 174
      },
      {
        "board": 56,
        "whiteSeed": 95,
        "blackSeed": 173
      },
      {
        "board": 57,
        "whiteSeed": 187,
        "blackSeed": 100
      },
      {
        "board": 58,
        "whiteSeed": 189,
        "blackSeed": 102
      },
      {
        "board": 59,
        "whiteSeed": 193,
        "blackSeed": 104
      },
      {
        "board": 60,
        "whiteSeed": 195,
        "blackSeed": 106
      },
      {
        "board": 61,
        "whiteSeed": 111,
        "blackSeed": 190
      },
      {
        "board": 62,
        "whiteSeed": 198,
        "blackSeed": 117
      },
      {
        "board": 63,
        "whiteSeed": 121,
        "blackSeed": 221
      },
      {
        "board": 64,
        "whiteSeed": 226,
        "blackSeed": 122
      },
      {
        "board": 65,
        "whiteSeed": 124,
        "blackSeed": 222
      },
      {
        "board": 66,
        "whiteSeed": 125,
        "blackSeed": 238
      },
      {
        "board": 67,
        "whiteSeed": 225,
        "blackSeed": 129
      },
      {
        "board": 68,
        "whiteSeed": 131,
        "blackSeed": 230
      },
      {
        "board": 69,
        "whiteSeed": 133,
        "blackSeed": 242
      },
      {
        "board": 70,
        "whiteSeed": 253,
        "blackSeed": 135
      },
      {
        "board": 71,
        "whiteSeed": 20,
        "blackSeed": 163
      },
      {
        "board": 72,
        "whiteSeed": 166,
        "blackSeed": 71
      },
      {
        "board": 73,
        "whiteSeed": 87,
        "blackSeed": 172
      },
      {
        "board": 74,
        "whiteSeed": 168,
        "blackSeed": 108
      },
      {
        "board": 75,
        "whiteSeed": 177,
        "blackSeed": 112
      },
      {
        "board": 76,
        "whiteSeed": 245,
        "blackSeed": 120
      },
      {
        "board": 77,
        "whiteSeed": 145,
        "blackSeed": 178
      },
      {
        "board": 78,
        "whiteSeed": 147,
        "blackSeed": 200
      },
      {
        "board": 79,
        "whiteSeed": 248,
        "blackSeed": 152
      },
      {
        "board": 80,
        "whiteSeed": 155,
        "blackSeed": 227
      },
      {
        "board": 81,
        "whiteSeed": 255,
        "blackSeed": 158
      },
      {
        "board": 82,
        "whiteSeed": 181,
        "blackSeed": 96
      },
      {
        "board": 83,
        "whiteSeed": 101,
        "blackSeed": 184
      },
      {
        "board": 84,
        "whiteSeed": 107,
        "blackSeed": 183
      },
      {
        "board": 85,
        "whiteSeed": 182,
        "blackSeed": 128
      },
      {
        "board": 86,
        "whiteSeed": 186,
        "blackSeed": 132
      },
      {
        "board": 87,
        "whiteSeed": 196,
        "blackSeed": 136
      },
      {
        "board": 88,
        "whiteSeed": 137,
        "blackSeed": 202
      },
      {
        "board": 89,
        "whiteSeed": 197,
        "blackSeed": 138
      },
      {
        "board": 90,
        "whiteSeed": 201,
        "blackSeed": 139
      },
      {
        "board": 91,
        "whiteSeed": 204,
        "blackSeed": 146
      },
      {
        "board": 92,
        "whiteSeed": 150,
        "blackSeed": 218
      },
      {
        "board": 93,
        "whiteSeed": 206,
        "blackSeed": 154
      },
      {
        "board": 94,
        "whiteSeed": 215,
        "blackSeed": 160
      },
      {
        "board": 95,
        "whiteSeed": 165,
        "blackSeed": 246
      },
      {
        "board": 96,
        "whiteSeed": 216,
        "blackSeed": 170
      },
      {
        "board": 97,
        "whiteSeed": 234,
        "blackSeed": 171
      },
      {
        "board": 98,
        "whiteSeed": 254,
        "blackSeed": 176
      },
      {
        "board": 99,
        "whiteSeed": 144,
        "blackSeed": 231
      },
      {
        "board": 100,
        "whiteSeed": 188,
        "blackSeed": 233
      },
      {
        "board": 101,
        "whiteSeed": 239,
        "blackSeed": 205
      },
      {
        "board": 102,
        "whiteSeed": 251,
        "blackSeed": 210
      },
      {
        "board": 103,
        "whiteSeed": 232,
        "blackSeed": 250
      },
      {
        "board": 104,
        "whiteSeed": 220,
        "blackSeed": 164
      },
      {
        "board": 105,
        "whiteSeed": 224,
        "blackSeed": 180
      },
      {
        "board": 106,
        "whiteSeed": 185,
        "blackSeed": 228
      },
      {
        "board": 107,
        "whiteSeed": 236,
        "blackSeed": 192
      },
      {
        "board": 108,
        "whiteSeed": 212,
        "blackSeed": 240
      },
      {
        "board": 109,
        "whiteSeed": 159,
        "blackSeed": 244
      },
      {
        "board": 110,
        "whiteSeed": 211,
        "blackSeed": 208
      },
      {
        "board": 111,
        "whiteSeed": 241,
        "blackSeed": 229
      },
      {
        "board": 112,
        "whiteSeed": 209,
        "blackSeed": null
      }
    ]
  }
] as const;
